### ISSUE TITLE
Add categories model for products

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#107]
This is to support https://github.com/appirio-tech/connect-app/issues/2139.

**Comment by coderReview** [comment]
Hello @vikasrohit is the category model already define in the app or we need to create it? If we need to create it what is the schema?

Thanks

**Comment by vikasrohit** [comment]
@coderReview we have the category model for project only, I mean we have the table `project_types` for managing the category of the projects which is right now we are using for categorizing the project templates as well. However, we can not use that for product templates as we are expecting different set of categories for the product templates. So, we have two options:
1. Add a new field in existing `project_types` table to support categories/types for the products as well. OR
2. Create new model/table `product_categories` to categorize the product templates.

I think, 2 is better to keep things simple and clean.

**Comment by coderReview** [comment]
**Scope:**

a) Add product category model with creation SQL

b) simple crud on the model (following permission model of projectType model) 

c) swagger/postman updates.

d) unit tests
