### ISSUE TITLE
Versioning of templates

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#109]
We need to think about version of templates and provide the ability to support multiple version of each template.

Updates:

We can achieve minimal versioning by following changes:
1. Add a new field called `version` to the `projectTemplate` and `productTemplate` models
2. Make the combination of `key` and `version` fields to be unique i.e. there can exists only one template per version per template type (we identify templates by their `key`).
3. Add new endpoints of these two models to serve existing use cases wit `version` and `key` in their URL e.g.
- `GET /v4/projectTemplates/{key}/versions` : Lists all versions of the given type of template
- `GET /v4/projectTemplates/{key}/versions/{version}` : Fetches the particular version of the given type of template
- `POST /v4/projectTemplates/${key}/versions` : Creates a new version of the given type of template
- `PATCH /v4/projectTemplates/${key}/versions/{version}` : Updates the specific version of the given type of the template
- `DELETE /v4/projectTemplates/${key}/versions/{version}` : Deletes the specific version of the given type of the template
4. User should still be able to use old `id` based endpoints, however, they all should be updated to enforce the validation for `key` and `version` combination as mentioned in 2.
5. Update the `GET /v4/projectTemplates` endpoint to return only the latest version of each of the template.
5. Same steps, 3-5, should be done for `productTemplate` model
6. All project templates in database has to be updated for using the `version` of the product template in `phases.products[i]` instead of `id`.
7. Update the project service `POST /v4/projects` endpoint to use the combination of `key` and `version` to uniquely identify the product template for each phase in the project. Right now it is using the `id` field to uniquely identify the product template.

fyi @RishiRajSahu @rmjmccormick @acshields @dmessing @vic-topcoder

**Comment by maxceem** [comment]
> 8\. Update the project service `POST /v4/projects` endpoint to use the combination of `key` and `version` to uniquely identify the product template for each phase in the project. Right now it is using the `id` field to uniquely identify the product template.

As I understand we would need for this:
- add new properties to the project model, both of them can be null
   - `templateKey`
   - `templateVersion`
- remove `templateId` from the project model
- create migration which would update all projects: populate `templateKey` and `templateVersion` and remove `templateId`
- NOTE, I guess we would need to reindex projects in ES after such change

After that, we would also have to update Connect App to use pair of `templateKey` and `templateVersion` when creating and loading projects instead of `teamplteId`.

@vikasrohit, if my understanding is correct here, I think the rest is clean to go.

**Comment by maxceem** [comment]
@vikasrohit currently, we can delete templates. Which now makes projects which use such templates broken.
- Should we check that template is not being used by any project before deleting it?
- For versions: should we check that particular version is not being used by any project before deleting it?

**Comment by vikasrohit** [comment]
> if my understanding is correct here, I think the rest is clean to go.

Sorry for responding late for this. Yes, your understanding is absolutely correct here. Do you have any other suggestions or questions around versioning? I mean, I just wrote the steps which I thought of at that time but I was not sure if these are all things required and if implementing these would serve our purpose.

One additional important requirement which we are looking here is to, automatically updating the versions of a template e.g. if a user updates the scope JSON for a project template with key `website` and version being `v4`, it should automatically increase the version to `v5` or `v4.1` and we should keep a finite number of versions in the system so e.g., we would discard `v1` - `v5` if we agree on keeping only 10 versions per template and user's current update moves version to `v15`.

> Should we check that template is not being used by any project before deleting it?

I think it would be good to have that check and we can still allow deleting such template if admin wants. We can ask admin to type some text to verify the intent.

**Comment by maxceem** [comment]
@vikasrohit as now we are doing refactoring of project templates into:
```
ProjectTemplate:
   links -> Form
   links -> PriceConfig
   links -> PlanConfig 
```

Maybe we can add versioning at the same time as I guess intead of adding versions to `ProjectTemplates`, we should add versions to `Form`, `PriceConfig` and `PlanConfig` now, so project template will refer them like this:

```
ProjectTemplate: {
   formKey: 'app',
   formVersion: 12,
   priceConfigKey: 'app',
   priceConfigVersion: 7,
   planConfigKey: 'app',
   planConfigVersion: 1,
}
```

What do you think?

**Comment by vikasrohit** [comment]
Yes, Agreed. So, may be we can design new models with versioning in mind at first place. Also, we might need to be ready for data migration of existing templates, although I think we can avoid that by keeping the existing fields of the project template as is for now and just taking care of new model in front end just like we take care of `v2` vs `v3` projects.

**Comment by maxceem** [comment]
1. What do you think about making versions just integer numbers `1, 2, 4, ...,N`?

2. Regarding automatic removing. I guess we not always can remove old versions because old versions could be used by some templates. Maybe something like this?
     - when we create a new version we check if there are any object versions which were created erlier than some amount of days and if they are not refered by any template - we remove these old object versions.

     Such approach woldn't force some certain amount of versions which may exist at each moment.
3. > Also, we might need to be ready for data migration of existing templates, although I think we can avoid that by keeping the existing fields of the project template as is for now and just taking care of new model in front end just like we take care of v2 vs v3 projects.

    As I understand to make the migration process similar to projects migration, we would need to add version property to projectTemplates, and after support handling of two versions client side.
    Maybe we can try to think about migrating imeediately? I guess if we do it now the process will look like this: add new models and update values of projectTemplates but not change the scheme for projectTemplates and only update values like this:
    Before
    ```js
     projectTemplate = {
        scope: {
           sections: [],
           wizard: {},
           basePriceEstimate: 123,
           baseTimeEstimateMin: 123,
           baseTimeEstimateMax: 123,
           priceConfig: {},
           preparedConditions: {},
           buildingBlocks: {},
           priceConfig-old: null,
           priceConfigOpt: null,
           addonPriceConfig: {},
        },
        phases: {
           'some-phase-id': {
              name: '',
              products: [],
           }
        }
     }
    ```
    After:
    ```js
     projectTemplate = {
        scope: {
           form: { key: 'app', version: 1 },
           priceConfig: { key: 'app', version: 1 },
           // the rest of properties which did go to the form or priceConfig
           baseTimeEstimateMin: 123,
           baseTimeEstimateMax: 123,
           priceConfig-old: null,
           priceConfigOpt: null,
        },
        phases: {
           planConfig: { key: 'app', version: 1 }
        }
     }

    form = {
       key: 'app',
       version: 1,
       scope: {
           sections: [],
           wizard: {},
           preparedConditions: {},
       }
    }

    priceConfig = {
       key: 'app',
       version: 1,
       config: {
           basePriceEstimate: 123,
           priceConfig: {},
           preparedConditions: {},
           buildingBlocks: {},
           addonPriceConfig: {},
       }
    }

    planConfig = {
       key: 'app',
       version: 1,
       phases: {
          'some-phase-id': {
              name: '',
              products: [],
           }
       }
    }
    ```

**Comment by maxceem** [comment]
@vikasrohit I've created the draft specification for project template refactoring, maybe you could have a look https://docs.google.com/document/d/16o1at1wMK_xvDysMa8fLghEUgIoDIf-5z1IzIBnowuk/edit#

**Comment by vikasrohit** [comment]
@maxceem I think if we do migration immediately, I would like to keep this structure for ProjectTemplate:

```
projectTemplate = {
    scope: {
       // as is
    },
    phases: {
       // as is
    },
    planConfig: { key: 'app', version: 1 },
    priceConfig: { key: 'app', version: 1 },
    form: { key: 'app', version: 1 }
 }
```

For new templates (after this refactoring), `scope` and `phases` would be null and for older ones, `form`, `priceConfig` and `planConfig` would be null.

For migration, may be we can provide an endpoint just like we have for project upgrade which allows us to selectively upgrade templates. What that endpoint would do is, move content from `scope` and `phases` to new models. And that upgrade endpoint would also allow specifying using existing form/priceConfig/planConfig and if user does not specify any one of them, it would extract the current content as new corresponding entity.

**Comment by maxceem** [comment]
@vikasrohit 

As I understand you prefer instead of migrating all the `projectTemplates` immediatelly do it selectively, so we will need to support two versions of `projectTemplates` in Connect in the next places:
    - Metadata editor `projectTemplate` old version
    - Metadata editor `projectTemplate` new version
    - Creating V2 projects: `productTemaplate` only one version
    - Creating V3 project: `projectTemplate` old version
    - Creating V3 project: `projectTemplate` new version
    - Viewing V2 project: `productTemaplate` only one version
    - Viewing V3 project: `projectTemplate` old version
    - Viewing V3 project: `projectTemplate` new version

The spec is ready as per my current understanding https://docs.google.com/document/d/16o1at1wMK_xvDysMa8fLghEUgIoDIf-5z1IzIBnowuk/edit#, it would be great if you could have a look. In particular there are some comments on the document with some questions I have.

PS I'd prefer to run challenges for Project Sevice and Connect separately, so as soon we agree on the changes for Project Servce - can run this part.

**Comment by vikasrohit** [comment]
> As I understand you prefer instead of migrating all the projectTemplates immediatelly do it selectively

**Comment by vikasrohit** [comment]
@maxceem I think we can close this one as we have the backend ready for versioning. If we don't have an issue for front end work, we can create that.

**Comment by maxceem** [comment]
Yes, this is done and so far there are no issues, except migration SQL script, that I've fixed today.
