### ISSUE TITLE
GET /v4/timelines returns 500 for non-manger users

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#119]
If we call `GET /v4/timelines` endpoint with any params using `pshah_customer` user, we will get error
```
[too_many_clauses] maxClauseCount is set to 1024
```

![image](https://user-images.githubusercontent.com/146016/43044181-3e0c77a6-8dd4-11e8-8ec9-8a0b643e5c5b.png)

**Comment by vikasrohit** [comment]
@maxceem it should be fixed now. I have made `reference` and `referenceId` fields required for GET /v4/timelines as it does not make sense to get timelines without these two fields. And our current use case would return only one timeline per `reference` and `referenceId` combination. Let me know if you think we have use case where these two filters should not be marked as required.

**Comment by maxceem** [comment]
@vikasrohit I think making them required makes sense. I didn't see any cases where we need to make a common request.

In this issue, I didn't highlighted it clear, that the main thing was, that I get this error, no matter what params I use. Even if I define `reference` and `referenceId` it works good for a manager, but returns the error `[too_many_clauses] maxClauseCount is set to 1024` for a customer.

Do you think now it's also fixed for customers? I'm in the middle of something, can try to check it myself later.

**Comment by vikasrohit** [comment]
IMO, it should fix it for every one because now it narrows the option of possible referenceId to be 1.

**Comment by maxceem** [comment]
Customer user still gets this error when he passes both `reference` and `referenceId`

For example: `/v4/timelines?filter=reference%3Dproduct%26referenceId%3D693` - request timelines of the product of the project which belongs to a customer. 
Server returns:
```
[too_many_clauses] maxClauseCount is set to 1024
```

When a customer doesn't pass any of `reference` or `referenceId` he gets `Please provide reference and referenceId filter parameters` as expected.

**Comment by gondzo** [comment]
This is only for pshah_customer user as he is the only customer user with more than 1024 projects. It's not an issue with other users. I don't think we need to fix this at the moment - we don't have customer/copilot users with such large number of projects.

**Comment by coderReview** [comment]
@vikasrohit I think here we might need to check how the query is being done to avoid such issues.

**Comment by vikasrohit** [comment]
Yes, @coderReview. Ideally, it should not look for all projects of a user, after making the reference and referenceId fields compulsory for the call.
