### ISSUE TITLE
Customer cannot create timelines and milestones

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#120]
Customers can create new projects in connect-app. During the creation of a new project connect-app also creates a new timeline and milestones. But customer user `pshah_customer` cannot create timelines and milestones

Server returns error 403:
```
You do not have permissions to perform this action
```

Timelines:
![image](https://user-images.githubusercontent.com/146016/43044169-070c6810-8dd4-11e8-98a4-966e8ff402a8.png)

Milestones:
![image](https://user-images.githubusercontent.com/146016/43044259-a628dd38-8dd5-11e8-896d-6747f5b448ea.png)

**Comment by vikasrohit** [comment]
@maxceem I think it would allow customer to create timeline, provided that the customer is the part of the team of the project. Please try creating a project using pshah_customer and then try to add timeline using the same user. It should work theoretically, if not it must be a bug.

**Comment by maxceem** [comment]
@vikasrohit yeah, it doesn't work for the projects, created by the `pshah_customer.

For example project http://local.topcoder-dev.com:3000/projects/6668

Product 666 belong to the project 6668:
![image](https://user-images.githubusercontent.com/146016/43046757-58130896-8e00-11e8-9fc1-7f0711d67752.png)

I try to make `POST https://api.topcoder-dev.com/v4/timelines` with the next data:
```json
{
  "param": {
    "name": "Welcome to the Visual Design phase",
    "description": "This is the first stage in our project. We’re going to show you the detailed plan in your timeline, with all the milestones.",
    "startDate": "2018-07-22T14:32:58+00:00",
    "endDate": "2018-08-15T14:32:58+00:00",
    "reference": "product",
    "referenceId": 666
  }
}
```

Server return error 403: `You do not have permissions to perform this action`.

**Comment by vikasrohit** [comment]
Fixed. It should be working now, hopefully. :)

**Comment by vikasrohit** [comment]
Although, we might not need to create individual milestones now, fixed the issue with permission check.
