### ISSUE TITLE
Support product reference for timelines

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#121]
Currently, timelines endpoint supports only `phase` and `project` to be a reference.

For connect-app we need to create timelines per product. But if we try to create a timeline with 
`reference=product` and `referenceId=<productId>` we will get a validation error from the server:
```
validation error: "reference\" must be one of [project, phase]
```

**Comment by vikasrohit** [comment]
It should have fixed already by https://github.com/topcoder-platform/tc-project-service/commit/4019c1d7fb912861684ecc2a701f3fe8cd515981, let me know if it is still not working.

**Comment by maxceem** [comment]
@vikasrohit you are right it already works. So I'm closing this issue.
