### ISSUE TITLE
Validate category fields in projectTemplate and productTemplate endpoints

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#125]
As of now, we have a category field in `projectTemplate` model and after completion of #124 we would have the similar field for `productTemplate`. Purpose of this ticket is to validate these fields from there respective lookup tables which are `project_types` and `product_categories` respectively.

fyi @coderReview

**Comment by vikasrohit** [comment]
@coderReview has this been accidentally reopened?

**Comment by coderReview** [comment]
yes, sorry

**Comment by coderReview** [comment]
I will close all fixed issues.
