### ISSUE TITLE
[$120] Project should be soft deleted

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#128]
As of now we are hard deleting the project while other entities in the same service are being soft deleted. We need to make sure that we are making soft delete for the projects as well.

Please check and fix if any other entity is still being hard deleted in the service.

fyi @coderReview

**Comment by coderReview** [comment]
All these entities are doing hard delete:

```
timelines
milestones
projectTemplates
projectMembers
productCategories
projects
projectTypes
milestoneTemplates
productTemplates
```

We need to update to do soft delete and remove them from get and list.

please confirm @vikasrohit

**Comment by morehappiness** [comment]
how to assign to me?

**Comment by coderReview** [comment]
@morehappiness Just remove open-for-pickup and assign yourself to issue. You should have access now

**Comment by coderReview** [comment]
Fixed permission

**Comment by morehappiness** [comment]
@coderReview I still can not do anything

**Comment by coderReview** [comment]
have you accepted the invitation

**Comment by coderReview** [comment]
do you want to fix this issue?  I can assign it to you in the meantime

**Comment by morehappiness** [comment]
Yes please

**Comment by coderReview** [comment]
Fixed?

**Comment by morehappiness** [comment]
Yes. I forgot to accept the invitation.

**Comment by coderReview** [comment]
A good example of soft delete is `phases` and `phaseProducts`

**Comment by morehappiness** [comment]
thanks

**Comment by coderReview** [comment]
@morehappiness please don't do soft delete for `projectType` and `projectCategory`.

**Comment by coderReview** [comment]
Update my comment above

**Comment by coderReview** [comment]
@morehappiness please check if the model is set to paranoid true. If yes no change is needed.

**Comment by coderReview** [comment]
I think only project is not soft delete.

**Comment by coderReview** [comment]
Please update the unit test to validate that the record is not deleted from db (do a find using paranoid: false). Let me know if you have any doubts.

**Comment by morehappiness** [comment]
does the soft delete operation appy to all the entities?  Or projectType and projectCategory exclusive as from your previous comment?

**Comment by morehappiness** [comment]
@coderReview any reply?

**Comment by coderReview** [comment]
> does the soft delete operation appy to all the entities? Or projectType and projectCategory exclusive as from your previous comment?

Yes.

> Also, there are some entities already soft-deleted. Such as ProjectPhase, should we do changes to use the approach in timeline?

Yes. We want to make them standard.

**Comment by coderReview** [comment]
@morehappiness don't push to the branch directly. Please fork repository and create PR.

**Comment by coderReview** [comment]
I have removed your commit and closed your PR.

**Comment by morehappiness** [comment]
Sorry for the misoperation

**Comment by coderReview** [comment]
no problem.

**Comment by morehappiness** [comment]
I see the bug bash page says it needs to pull request to dev branch. Is that right?

**Comment by coderReview** [comment]
That is a generic instruction. The challenge page says to use `feature/timeline-milestone` branch.

**Comment by vikasrohit** [comment]
Working fine for the specified requirements.
