### ISSUE TITLE
[$100] Need new endpoint to copy milestone templates from one template to another

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#129]
**New endpoint** : POST /v4/productTemplates/{templateId}/milestones/clone
**Payload**:
```
{ param: { sourceTemplateId: 123 } }
```
It should clone all the template from template identified by `sourceTemplateId` to the template identified by `templateId`.

**Deliverables**: PR with following changes
1. Updated source code
2. Unit tests for the new endpoint
3. Updated Swagger doc
4. Updated Postman collection

fyi @coderReview @RishiRajSahu

**Comment by mhikeo** [comment]
Hi. I cannot assign it to myself yet but I'm taking this up. Thanks.

**Comment by coderReview** [comment]
@mhikeo how is it going? when do you plan to submit?

**Comment by mhikeo** [comment]
@coderReview Submitting within the hour.

**Comment by vikasrohit** [comment]
@coderReview @mhikeo merging the PR for now to reduce the possibilities of conflicts with other fixes. I have made request of small change in the PR which is needed to be worked on before we close this issue. We will verify the changes in dev env and there after will close the issue if found working.
