### ISSUE TITLE
[$40] Setting StartDate for default and explicitly added phases

### ISSUE THREAD

**Issue by RishiRajSahu** [topcoder-platform/tc-project-service#130]
Currently, we don't set start date of a phase during creation. We need to persist start date as well during creation of phase whether its default phase for a project or its a newly added phase.

fyi @vikasrohit @rmjmccormick @acshields 

**Requirements**:
1. Update `POST /v4/projects` endpoint to set the current date as phase `startDate` and set the `endDate` as `startDate + duration`.
2. Update unit tests to validate the startDate and endDate after project creation

**Comment by vikasrohit** [comment]
@RishiRajSahu we won't need to update the `add phase` endpoint because at that its the caller who sends the data for the phase, so caller can send the dates as required.

**Comment by architectt1** [comment]
https://github.com/topcoder-platform/tc-project-service/pull/138

**Comment by vikasrohit** [comment]
Working fine for the specified requirements.
