### ISSUE TITLE
[$40] Add new file url to bus api event

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-project-service#131]
Bus event for uploaded files should contain the file url. Url format is `https://connect.topcoder.com/projects/{projectId}/attachments/{attachmentId}`. Domain should be read from config (topcoder.com or topcoder-dev.com)

chenge should be made at https://github.com/topcoder-platform/tc-project-service/blob/1602c6c53686642b8d08dc440b1a825bb4b60e63/src/events/busApi.js#L170

**Comment by architectt1** [comment]
https://github.com/topcoder-platform/tc-project-service/pull/137
