### ISSUE TITLE
[$40] Project event links in bus event

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-project-service#132]
All project related bus events should contain the connect project url. Url format is https://connect.topcoder.com/projects/{projectId}. Domain should be read from config (topcoder.com or topcoder-dev.com)

change should be made at https://github.com/topcoder-platform/tc-project-service/blob/dev/src/events/busApi.js

**Comment by architectt1** [comment]
https://github.com/topcoder-platform/tc-project-service/pull/136

**Comment by vikasrohit** [comment]
@coderReview merged the PR.
