### ISSUE TITLE
[$60] Postman clean up and seed fix

### ISSUE THREAD

**Issue by coderReview** [topcoder-platform/tc-project-service#133]
## Postman 

- Remove unnecessary endpoints in `Timeline` folder because of #119 changes.

- Fix ProjectType error in create

- Fix ProductTemplate error in create

- Move tests under issueXX to correct folder. If unnecessary remove

- Organize the rest of folder and make sure all testing are working properly

## Seed fix

- Fix the command `npm run seed`

**Comment by simranb86** [comment]
Hi Can you assign this to me and proivide me access to repo ?

**Comment by simranb86** [comment]
Ok i see i hav rights to repo - please assign me when you get online as i cannot assign myself. 

FYI all -I am starting work on this.

**Comment by simranb86** [comment]
@coderReview please assign me when you get online

**Comment by simranb86** [comment]
Thanks @vikasrohit

**Comment by simranb86** [comment]
Sorry not been able to setup the app locally. Can we open up for others who have setup ready?

**Comment by coderReview** [comment]
what are your issues?

**Comment by thiyagu06** [comment]
@simranb86 , docker is running your at the port 5432. Change the port and try, It should work. If still you are interested to working on this issue and pls re assign it to yourself

**Comment by simranb86** [comment]
Thanks @thiyagu06 - it's ok. I moved to other task.

**Comment by vikasrohit** [comment]
just fyi @simranb86 I think it needs `NODE_ENV=local` to run it locally.

**Comment by vikasrohit** [comment]
@coderReview Closing as it is marked as accepted.
