### ISSUE TITLE
[$30] GET /v4/projects endpoint always returns the attachments data

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#140]
[list.js](https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projects/list.js#L137) should not return attachments data if not requested as [list-db.js](https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projects/list-db.js#L61) is doing.

Should update the unit tests accordingly.

**Comment by vikasrohit** [comment]
Please accept the invitation, once done I will assign you.

**Comment by narekcat** [comment]
@vikasrohit I accepted the invitation, thank you.

**Comment by narekcat** [comment]
@vikasrohit I setup application, and try to create project, but there are problem with creating direct project (https://api.topcoder-dev.com/v3/direct/projects/). It responses with status code 401 and message "Valid credentials are required to access this resource.". I try with Bearer code provided in README.md and also try with Bearer code in default.json, bet result is same. Are there any problems with direct project service endpoint ? Are this Bearers wrong ?

**Comment by vikasrohit** [comment]
You can skip direct call. Either resolve empty promise instead of calling
direct or remove that block for your local setup.

**Comment by narekcat** [comment]
@coderReview I use `feature/timeline-milestone` branch, but ok I'll do like @vikasrohit said. And one more thing. Today I have setted up application, this was first time that I were working on this project, that's way setup takes more time. The last issue that I were working on is issue with direct project endpoint. It took about 3 hours to find it out and now I need more time to finish bug. Can I work on it a little longer ?
