### ISSUE TITLE
Product templates error

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-project-service#145]
Request URL:https://api.topcoder-dev.com/v4/productTemplates/ is returning 500 at the moment with error message: `"SequelizeDatabaseError: column "category" does not exist`

Can we deploy a stable branch to dev as it's a blocking issue for connect app development @coderReview @vikasrohit

**Comment by coderReview** [comment]
@gondzo when was this column created in *dev* branch?

**Comment by gondzo** [comment]
not in dev branch - in dev environment. feature/timeline-milestones gets deployed to dev on each commit.
I have redeployed aa61e23730702685504af3481845a49e647c6d7a and the api looks good now, but any new commit to feature/timeline-milestone will deploy the latest again and it will break things again. I guess the columns has to be created in dev database first. @vikasrohit can you run the latest migrations on dev database?

**Comment by coderReview** [comment]
@gondzo it was an incorrect commit. I've remove it. thanks

**Comment by vikasrohit** [comment]
Thanks for sorting it out guys.

**Comment by gondzo** [comment]
Thanks @coderReview
