### ISSUE TITLE
Milestone status

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-project-service#147]
Looks like available milestone statuses are now same as project status statuses, i.e.
```
DRAFT: 'draft',
  IN_REVIEW: 'in_review',
  REVIEWED: 'reviewed',
  ACTIVE: 'active',
  COMPLETED: 'completed',
  PAUSED: 'paused',
  CANCELLED: 'cancelled',
```

but in frontend we have very different list
```
PLANNED: 'planned',
  ACTIVE: 'active',
  BLOCKED: 'blocked',
  COMPLETED: 'completed',
```

@vikasrohit which one is right?
Also, how is a milestone activated? It's created as 'reviewed' by default, but there are no options to activate a milestone in frontend. Should the first milestone be active by default?

**Comment by vikasrohit** [comment]
@gondzo we are keeping exact same status for milestones and phases as we are for project. However, we are mapping the these to front end statuses which are more logical for customers. So, mapping is as follows:
`draft`, `in_review` => `Unplanned` (we might have to add this to front end if not already there)
`reviewed` => `Planned`
`active` => `In Progress`
`paused` => `Blocked`
`completed` => `Completed`
`cancelled` => `Cancelled` (I think this also needed to be added to the front end.

You can related it better [here](https://github.com/appirio-tech/connect-app/blob/dev/src/config/constants.js#L369).

> but there are no options to activate a milestone in frontend

We can activate the first milestone when the phase is marked as active. And there after each milestone has button to mark it complete which activates the next milestone.

**Comment by gondzo** [comment]
> We can activate the first milestone when the phase is marked as active

Should this be done is backend or frontend? Backend makes more sense, but as we're keeping phases and timelines decoupled, this might be tricky? @vikasrohit

**Comment by vikasrohit** [comment]
Yes, I would prefer on the frontend to keep timelines as much decoupled as we can. I am not sure what can be tricky here if we do it on the frontend. I think we missed to add an issue for that in front end.

**Comment by gondzo** [comment]
it's not tricky on frontend, only in backend. anyhow, it's implemented in frontend now https://github.com/appirio-tech/connect-app/commit/dcb401117e7f678aba68aa38d8e6f75aa90ddf30
