### ISSUE TITLE
[$50] Remove validation for keeping milestone dates in bound to the timeline dates

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#148]
As per discussion [here](https://github.com/appirio-tech/connect-app/issues/2245#issuecomment-408668577) we need to remove the validations in `PATCH /v4/timelines/123/milestones/1234`. Instead it needs to update the timeline's bounds accordingly.

**Requirements:**
1. Remove validation for bounding the milestone's dates within timelines' dates
2. Update timeline's dates as per change in milestone i.e. if change in milestone dates requires the timeline's end dates to be extended, extend it or if it requires it to be contracted, contract it.
3. Stop accepting `startDate` and `endDate` in this method essentially deprecating the updates to the milestone's `startDate` and `endDate`.
4. Update unit tests to validate the changes.
5. Update the swagger and postman docs 

fyi @RishiRajSahu @gondzo 

@coderReview Adding it to the bug bash.

**Comment by vikasrohit** [comment]
@Gauravseta @architectt1 we need this task to be wrapped within next 12-18 hours. Let me know if it is possible for you guys, I would assign the task immediately.

**Comment by Gauravseta** [comment]
@vikasrohit not possible for me as of now. please assign it @architectt1

**Comment by vikasrohit** [comment]
Okay. Thanks for the update @Gauravseta

**Comment by vikasrohit** [comment]
@architectt1 I think you have already made half of the changes in your PR #144 . Could you please just include some other minor things as listed in the description of this issue? Also, I am adding review to the PR considering that this issue is also included in that.

**Comment by architectt1** [comment]
@vikasrohit Yup, sounds good, I'll try to make it within that timeframe.

**Comment by architectt1** [comment]
@vikasrohit https://github.com/topcoder-platform/tc-project-service/pull/144 contains changes for both revised https://github.com/topcoder-platform/tc-project-service/issues/127 and this issue.
