### ISSUE TITLE
[$60] After project creation, ES index is not updated

### ISSUE THREAD

**Issue by coderReview** [topcoder-platform/tc-project-service#150]
When creating a project it's not showing in `list` and `get` endpoints.

Check if ES index is being correctly updated.

From @vikasrohit 

> I made certain changes last week in project creation end point in term of promise and transaction handling. That can be culprit.

**Comment by vikasrohit** [comment]
@Gauravseta any progress?

**Comment by vikasrohit** [comment]
@Gauravseta @coderReview It seems to be working fine for me. Closing the issue for now, let me know if you still see the issue.
