### ISSUE TITLE
Update dates of hidden milestones as well when cascading the changes in a milestone

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#156]
As of now we are not considering the hidden milestone for any processing for cascading changes when a milestone's dates are updated. Rather we need to consider that hidden milestone as well, however, we should not mark that active and instead mark the first non hidden milestone, after the current milestone, as active. We should update the start/end dates of the hidden field as we are doing for non hidden milestones.

**Comment by RishiRajSahu** [comment]
Thanks @vikasrohit , did the needful changes on UI side as well and pushed to dev.
