### ISSUE TITLE
Move all supporting entities endpoints under `/v4/projects/metadata`

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#161]
As of now we are hosting all supporting endpoints as root endpoints parallel to the `/v4/projects` e.g.
- `/v4/projectTemplates`
- `/v4/productTemplates`
- `/v4/productTemplates/123/milestones`
- `/v4/projectTypes`
- `/v4/productCategories`

we need to move them to 

- `/v4/projects/metadata/projectTemplates`
- `/v4/projects/metadata/productTemplates`
- `/v4/timelines/metadata/milestoneTemplates?reference='product'&referenceId=123` (Please note it is using `timelines` as root entity because milestone and their templates more relates to the timeline than `projects` and this new location of endpoint would also require the way it behaves. Now it would not provide milestone templates with path param, rather it would ask for 2 new query params `reference` and `referenceId` and would search the milestone templates for those two params)
- `/v4/projects/metadata/projectTypes`
- `/v4/projects/metadata/productCategories`

Also, we need to create a new endpoint which returns all the metadata as `GET /v4/projects/metadata` which would be public endpoint and would return all of the above endpoints' data without any filter.

**Comment by ngoctay** [comment]
Regarding to the 3rd one  `/v4/timelines/metadata/milestoneTemplates?reference='product'&referenceId=123`

We also need to change the table name "product_templates" to "milestone_templates", right?

**Comment by vikasrohit** [comment]
Yes, but we kept that part as separate [issue](https://github.com/topcoder-platform/tc-project-service/issues/151) for better tracking. So you can finish that first and then come back to this.

**Comment by vikasrohit** [comment]
Closing. @gondzo please feel free to tag it as per convenience for payments.
