### ISSUE TITLE
Add ability to create product in phase creation call

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#163]
`POST /v4/projects/123/phases` should be able to create product as per specified `productTemplateId` (new param in post body). If it is not passed, skip creation of product i.e. it should be backward compatible.

**Comment by ngoctay** [comment]
@vikasrohit

How can we populate a new product from productTemplateId?
I checked "productTemplate.js" and "phaseProduct.js", but they have different properties.

**Comment by vikasrohit** [comment]
@ngoctay Good observation, however, we just need few fields from `productTemplate` to `phaseProduct` which are:
1. name => `productTemplate.name`
2. templateId => `productTemplate.id` or simply the passed `productTemplateId`
3. type => `productTemplate.key`

Basically we want to get rid of this extra API call when creating phase and want to achieve the results in single call.

**Note:** Please return the newly created phase with the product created under field `products` as the only element in the array.

**Comment by vikasrohit** [comment]
Closing as working fine as per given requirements.

@gondzo Please feel free to tag it as per convenience for payment.
