### ISSUE TITLE
New authorization scheme for project creation endpoint

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#171]
To support a new use case, where we need to create projects for inactive users, we need to implement a new auth scheme in project service and use that only for project creation endpoint to allow the creation of projects by inactive users as well.

Details:
1. We will look for `Authorization` header
2. Technically it would still be using `Bearer` auth scheme but its value would not be a jwt token this time, rather it would be a simple string with following pattern like `userId_<userId>` i.e. `useId_` as prefix to the actual `userId`.
3. if we find the bearer token starting with `userId_`, we should not use the jwt auth middle ware from `tc-core-library-js` to validate the token and rather use custom logic.
4. if the passed `userId` is inactive (we can query that using admin access to the identity api), we should authorize the user and if `userId` is active, we need to throw 403 with appropriate message.

**Comment by ngoctay** [comment]
@vikasrohit 
1. Only for project creation endpoint, right?
2. "we can query that using admin access to the identity api", can you provide more details on on how to access the identity API?

**Comment by gondzo** [comment]
@vikasrohit does identity api support m2m tokens? do we have a clientId/secret that we could use?

@ngoctay I think identity service endpoint is v4_api/users. Is this correct @vikasrohit ?

**Comment by vikasrohit** [comment]
@ngoctay [this](https://github.com/topcoder-platform/tc-project-service/blob/dev/src/util.js#L294) should be the helper function you should be using to get user's status.

**Comment by vikasrohit** [comment]
@gondzo I think m2m are now supported by identity, however, if our current api is not using m2m to get system user token, we can still go with the existing method of clientId and secret.

**Comment by ngoctay** [comment]
@vikasrohit 
Thanks for the helper function.

Is there any dev identity API endpoint so that I can set the env?

**Comment by vikasrohit** [comment]
Yes, there is. It should be `https://api.topcoder-dev.com/v3`, however, it won't work on your local because you won't have client id and secret. You can test this on local by mocking the endpoint while unit testing.

**Comment by ngoctay** [comment]
Do you have any Swagger or Postman for the Identity API?
I don't know any about the request/response.

**Comment by vikasrohit** [comment]
@ngoctay this should help.
```
getStub.withArgs(`${config.get('identityServiceEndpoint')}users`, getUsersOpts).resolves({
  data: { result: { status: 200, content: [{ id: 1, ..., active: false }] } },
});
```

**Comment by ngoctay** [comment]
@vikasrohit 
Just curious. 
Anybody can easily guess a userId and invoke `POST /projects` with `Bearer userId_<userId>`.
That is not quite secured.

**Comment by ngoctay** [comment]
Please check the above commit.
Note that we have a new config `whitelistedOriginsForUserIdAuth` which stores the JSON string array of the whitelisted origins (similar to `validIssuers`)

**Comment by vikasrohit** [comment]
Seems good to me. I think it is easy to send `Origin` header as required by using automation tools like Selenium or bare `cURL`, but it is good to have the safeguard in place.
@ngoctay I didn't see the usage of the `userIdAuth` middleware in the change set, though.

**Comment by ngoctay** [comment]
Please check

https://github.com/topcoder-platform/tc-project-service/blob/991f2f36d0a5690c8bddff743e8722d6a93b3408/src/routes/index.js#L53:L65

**Comment by vikasrohit** [comment]
Yep, got it. I think it was not showing this change in the particular commit [link](https://github.com/ngoctay/tc-project-service/commit/991f2f36d0a5690c8bddff743e8722d6a93b3408).

**Comment by vikasrohit** [comment]
Closing. @gondzo Please tag it as per your convenience for payments.
