### ISSUE TITLE
New bus events for milestone notifications

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#172]
Need to support few new events for milestones similar to what we did for project plan earlier in https://github.com/topcoder-platform/tc-project-service/pull/110.

Current list of events is:

`notifications.connect.project.phase.milestone.transition.active` => when milestone is marked as active
`notifications.connect.project.phase.milestone.transition.completed` => when milestone is marked as complete
`notifications.connect.project.phase.milestone.waiting.customer` => when milestones are waiting for customers's input (this might be tricky to identify because every milestone type has different way to identify that it is waiting for customer input and that is stored in `details` json)

**Comment by ngoctay** [comment]
@vikasrohit @gondzo 
I will make a commit for the first 2 events.
For the last one (waiting.customer), will leave a TODO in the code so that we can tackle it later when we have more details.

**Comment by vikasrohit** [comment]
@ngoctay can you please raise the `...waiting.customer` event when we find `details.metadata.waitingForCustomer` flag to exist and equal to `true`? As of now, we don't have a unique way to identify that a milestone is waiting for customer input, so we are thinking of keeping a new flag at mentioned level to capture this details. This field would be updated by front end. Ideally, we don't want to parse the `details` field in backend but I think we are good in this case as it would be a standard flag across milestones and we would keep `details.content` as milestone specific data which we would never parse on backend.

**Comment by vikasrohit** [comment]
It was not working for `active` event when the milestone is made active as cascaded effect after marking previous milestone as `completed` and this was happening because we were using `cascadedUpdates` instead of `cascadedUpdates.milestones` to iterate over milestones updated via cascade. After fixing that it is working fine now for `active` and `completed` events,  however, we need to do some changes in front end to validate the `waiting.customer` event.
Marking the issue closed. Will take care of `waiting.customer` event separately after front end changes.
@gondzo please feel free to tag it as per convenience for payments.
