### ISSUE TITLE
Project List should filter out cancelled / deleted projects by default.

### ISSUE THREAD

**Issue by parthshah** [topcoder-platform/tc-project-service#18]

**Comment by fnisen** [comment]
@parthshah If you check out the status filters, I've had Luis add an "Open" status in there. It's a "derived" status that I'd like to use to show all projects except those that are Completed or Canceled. We can use the "Open" status as the default filter.

**Comment by parthshah** [comment]
I think it's best to handle such derived status on the Client instead of the API layer.

**Comment by fnisen** [comment]
Sure, implementation is up to you. You killed the original issue in connect-app, so this is the only place I could comment. : )

**Comment by parthshah** [comment]
I believe this issue has since been resolved. Please re-open if you think otherwise.

**Comment by fnisen** [comment]
@parthshah there is no option to re-open, only Comment. This one is still an open issue, and actually the Open status is not working right now: https://github.com/appirio-tech/connect-app/issues/618. I'd like it to be the default status, instead of "All Statuses."
