### ISSUE TITLE
Reuse code for ES mapping in elasticsearch_sync.js and project-create-index.js

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#181]
Currently, mapping configuration for ElasticSearch is fully described two times in https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/admin/project-create-index.js#L31-L296 and in https://github.com/topcoder-platform/tc-project-service/blob/dev/migrations/elasticsearch_sync.js#L32-L302

It's quite easy to forget to update one of them and also is hard to understand if they are in sync or no. So it would be probably better to reuse one mapping config in both places.

The only concern I have is that one of the in `migration` (kind of auxiliary tools) folder and another one in `src` folder.

**Comment by vikasrohit** [comment]
@maxceem Yep, I am aware of that. And reason for keeping both of them right now are two things:
1. We are not using `elasticsearch_sync.js` for our production environment. We mostly use it in local environment for cleaning the ES index.
2. ES schema is auto right now i.e. ES would add the field into the schema when first time it would index that field.

**Comment by maxceem** [comment]
Got it @vikasrohit. So I'm closing the issue, as looks like we don't have an immediate solution for this.
