### ISSUE TITLE
Event `connect.action.timeline.milestone.waiting.customer` is not created

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#231]
When we come to the last **Delivery** milestone in any project in Connect App we update the last milestone as `"waitingForCustomer": true`:
```
{
  "param": {
    "details": {
      "metadata": {
        "waitingForCustomer": true
      },
      "prevMilestoneType": "generic-work"
    }
  }
}
```

In this case, project service has to trigger the `connect.action.timeline.milestone.waiting.customer` event. But for some reason it doesn't happen, even though respective code looks correct:
https://github.com/topcoder-platform/tc-project-service/blob/dev/src/events/busApi.js#L517-L520

**Comment by vikasrohit** [comment]
Should be fixed now by https://github.com/topcoder-platform/tc-project-service/commit/22415e4cc8f28c6d4b4c16f850674b1d463b891d
