### ISSUE TITLE
[$120] Don't let invite user by email if he is already in the team or already invited

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#234]
### Actual behaviour
Example, I'm already is a Manager in **Topcoder team** of this project https://connect.topcoder-dev.com/projects/7709

I invite myself to the **Project Team** using email my address and server accepts my requests and creates an invitation.
![image](https://user-images.githubusercontent.com/146016/51454568-50cad400-1d80-11e9-8346-f8d44d898f19.png)

After I reload the page I got invitation popup even though I'm already in the Topcoder team.

![image](https://user-images.githubusercontent.com/146016/51454610-87085380-1d80-11e9-9d20-ef5e5ba783eb.png)

If I click **Join Project** I would get error that I'm already in the team.

### Expected behaviour
When we invite user by email which is already in the Topcoder or Project Team, server should reject such request, don't create invitation and return an error, that a user with such an email is already in the team.

This issue is somehow connected with https://github.com/topcoder-platform/tc-project-service/issues/233

fyi @RishiRajSahu

**Comment by vikasrohit** [comment]
@maxceem I think this one does not exist any more. Let me know if we can close this.

**Comment by vikasrohit** [comment]
@maxceem can we close this?

**Comment by maxceem** [comment]
@vikasrohit I think this is fixed client-side so this issue would never happen in the real life, but it's not fixed server-side.

**Comment by vikasrohit** [comment]
Okay, then we should get it implemented in backend as well. Marking this issue for 2.4.13 release. I am thinking of a quick bug bash for that milestone.

**Comment by maxceem** [comment]
Note we can invite several members at once, using handles and emails. When we invite user which is already in the team we have to return emails, for which invitations are failed in the response inside `failed` property, the same we do now for other errors. While successful invitation should be created as now.

See we return failed property if there are any invitations failed https://github.com/topcoder-platform/tc-project-service/blob/cf18/src/routes/projectMemberInvites/create.js#L292

See an example, where we populate such the failed list: https://github.com/topcoder-platform/tc-project-service/blob/cf18/src/routes/projectMemberInvites/create.js#L124

For the error message use the next text: `User with such email is already a member of the team.`.

We should create a unit test to validate this case.

**Comment by romitgit** [comment]
Please assign this issue to me

**Comment by maxceem** [comment]
@romitgit assigned.
To setup project locally you would need to set some environment variables as per [README](https://github.com/topcoder-platform/tc-project-service), you can find them on the [forum](https://apps.topcoder.com/forums/?module=Thread&threadID=939807&mc=1#2350618) of the [challenge](https://www.topcoder.com/challenges/30095031).

**Comment by romitgit** [comment]
@maxceem thanks. Will look into that.

**Comment by maxceem** [comment]
Thanks, just would like to remind that as per our [Bug Bash rules](https://www.topcoder.com/challenges/30095031), the submission PR should be created during 12 hours, or issues may be unassigned.

**Comment by romitgit** [comment]
@maxceem I'm not able to start the project. Getting dtrace-provider module not found error. Some help would be really appreciated. Thanks
![Screenshot 2019-07-04 at 10 29 20 PM](https://user-images.githubusercontent.com/8111864/60681033-45d9ab00-9eab-11e9-9734-b37ffb444b3f.png)

**Comment by romitgit** [comment]
@maxceem  I'm finished with the task. Just confused on where to raise the PR. Not able to commit anything as of now.

**Comment by romitgit** [comment]
It’s done and ready for review. Here is the PR link - https://github.com/topcoder-platform/tc-project-service/pull/330

**Comment by maxceem** [comment]
@romitgit I've reviewed your PR, please have a look https://github.com/topcoder-platform/tc-project-service/pull/330#pullrequestreview-258769150

**Comment by romitgit** [comment]
@maxceem I have made the changes and here is the pull request https://github.com/topcoder-platform/tc-project-service/pull/341

**Comment by maxceem** [comment]
Thank you @romitgit I'll check it out.

**Comment by maxceem** [comment]
@romitgit I've checked your new PR, please have a look on the review https://github.com/topcoder-platform/tc-project-service/pull/341#pullrequestreview-261054298

**Comment by romitgit** [comment]
@maxceem  I have made the changes, please review.

**Comment by romitgit** [comment]
@maxceem I am done with the changes. Please review

**Comment by maxceem** [comment]
In the provided PR more cases have been fixed, than initially required in the issue description. So the prize for this issue has been raised to $120.
The next cases are handled:
- returns errors when we invite already a member by email
- returns errors when we invite already a member by userId
- returns errors when we invite already invited by email
- returns errors when we invite already invited by userId
