### ISSUE TITLE
Error "Project members can only update invites for themselves"

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#235]
When I invite user `@maxceem` to the **Project Team** and after use user `@maxceem` to login and accept an invitation, I get error `Project members can only update invites for themselves`.

But I'm trying accepting an invitation for user `@maxceem` using user `@maxceem`.

fyi @RishiRajSahu

**Comment by vikasrohit** [comment]
Good to log this one. We have faced this for some users as well. Our investigation shows that this error mostly happens when there is difference in email of the user in our two systems (identity and member). Let me check if it is the same case for your user as well.

**Comment by vikasrohit** [comment]
@maxceem Just checked your email seems to be in sync everywhere. So, we definitely need to track down why it is not allowing you to add yourself to the team.

**Comment by maxceem** [comment]
@vikasrohit I've found the root of the issue. The endpoint https://api.topcoder-dev.com/v3/users?filter=id%3D40035291 return email as `"undefined"`:
```
{
    "id": "-4c9026f0:168717a447f:-3b8e",
    "result": {
        "success": true,
        "status": 200,
        "metadata": null,
        "content": [
            {
                "id": "40035291",
                "modifiedBy": null,
                "modifiedAt": "2019-01-21T22:37:43.000Z",
                "createdBy": null,
                "createdAt": "2014-07-15T02:23:11.000Z",
                "handle": "maxceem",
                "email": "undefined",
                "firstName": "",
                "lastName": "",
                "credential": {
                    "activationCode": "13F4RWNRI6A",
                    "resetToken": null,
                    "hasPassword": true
                },
                "status": "A",
                "country": null,
                "regSource": "http://www.topcoder.",
                "utmSource": "",
                "utmMedium": "",
                "utmCampaign": "",
                "roles": null,
                "ssoLogin": false,
                "active": true,
                "profile": null,
                "emailActive": true
            }
        ]
    },
    "version": "v3"
}
```

That's why when make the next check https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projectMemberInvites/update.js#L70 it fails.

Though I'm not sure why identity service returns `"undefined"`.

**Comment by maxceem** [comment]
I have a wild guess why it could happen. I've tested changing email with this user.
I've requested changing email but I didn't finish the process. Instead, I've just reactivated my user using admin panel.

**Comment by vikasrohit** [comment]
@maxceem just to be on same page, you are testing this in dev environment, right? I verified your email in production though. I just checked in dev env and found that your email is set as undefined some how. I just updated that, you can try now testing the invite again.
From my investigation, every time this issue is related to inconsistency in email between the invite and the user's actual email.

**Comment by maxceem** [comment]
> you are testing this in dev environment, right?
I've tested it on DEV environment.

> I just updated that, you can try now testing the invite again.
It works now for my account.

@vikasrohit do I get it right that we still have this issues on PROD and this is caused by?
> every time this issue is related to inconsistency in email between the invite and the user's actual email.

**Comment by maxceem** [comment]
I get this use again for `pshah_customer` user on DEV for this project https://connect.topcoder-dev.com/projects/7839/

**Comment by vikasrohit** [comment]
It is again inconsistent email for the user. I have tried to fix this @maxceem , try it now.

**Comment by maxceem** [comment]
@vikasrohit 
Didn't help so far:
- project https://connect.topcoder-dev.com/projects/7839/
- user `pshah_customer`
- cannot accept invitation
