### ISSUE TITLE
Support filtering project list using substring for id, name, REF, customers and managers

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#245]
To support the functionality described in this issue https://github.com/appirio-tech/connect-app/issues/2804 we have to support the ability to filter results of `GET /projects` endpoint using additional criteria.

#### Here is how the task looks from the point of view of Connect App:
- `ID`: User can type in a full ID or a portion (Ex. “55..) and all results matching that ID should be filtered.
- `Project name`: User can type in a full name or a portion (Ex. Eaton…) and all results matching that name should be filtered.
- `Reference Code`: User can type in a full code/tag or a portion (Ex. Zur…) and all results matching that name should be filtered. 
- `Customer`: Customer name should be filterable. User can type in a full name or a portion (Ex. Jim…) and all results matching that name should be filtered.
- `Managers`: Managers should be filterable. User can type in a name/handle and all results matching that should be filtered.

Implementation details should be added here as some of these filters cannot be done directly.

fyi @vikasrohit

**Comment by maxceem** [comment]
As all the data we want to filter by is added to Elastic Search index we can filter by all of these properties.

**Comment by maxceem** [comment]
As we already have filter by `id` which can be done by equality comparison `id=1234` where we compare the whole id. Or we can provide the list of id `id=in(1234,5678,9012)`.

For the new feature we can use syntax which would well matched with ES syntax:
- `id=12*` - find all projects with ids starts from `12`, `id=*12` - find all projects with id finishied with 12, `id=*12*` find all projects with id containing 12. While the current syntax `id=12` will find only project with id which equals to 12 as it's done now.

Same for filters for other properties.

**Comment by vigneshTheDev** [comment]
> As all the data we want to filter by is added to Elastic Search index we can filter by all of these properties.

Looks like Customer/Manager names are not available in elastic search index. Should we query the db for these?

**Comment by maxceem** [comment]
I thinkg they have to be in the ES, as per source code:
- on project creation: https://github.com/topcoder-platform/tc-project-service/blob/dev/src/events/projects/index.js#L38
- on member adding: https://github.com/topcoder-platform/tc-project-service/blob/dev/src/events/projectMembers/index.js#L85

Note, sometimes member API fails to respond with correct data and for some project we wouldn't have this data. But I guess locally you use mocked member API, so it should always work.

**Comment by vikasrohit** [comment]
@maxceem Closing the issue. We would take care of including ID in search later.
