### ISSUE TITLE
Can we remove test seed script?

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#276]
We have some script which may be called by `npm run seed` https://github.com/topcoder-platform/tc-project-service/blob/feature/seed-projects/src/tests/seed.js#L1.

I don't find any place or documentation on when it should be called. But it looks like it was created to be called before tests. But I don't see we call it now during tests.

Is there anybody knows the purpose of this script? Maybe we can safely remove it?

cc @vikasrohit

**Comment by vikasrohit** [comment]
Lets leave it as is for now @maxceem as it seems to be updated with latest models as well and it might be helpful in local setup. What do you think?

**Comment by maxceem** [comment]
@vikasrohit we have a new script `npm run demo-data` which populates metadata by copying data from the DEV env. And also it creates demo projects.

So these two scripts currently duplicate the functionality of each other.

The new script creates demo data in a more reliable way using API in comparison with the old one which is writing directly to the DB.

I don't use the old script and don't suggest using it in the challenges. But if you or anybody else uses it, we can keep it for sure.

**Comment by vikasrohit** [comment]
Okay. Lets remove it to avoid confusion. We can alway get it back from git history if required.

**Comment by maxceem** [comment]
Removed via https://github.com/topcoder-platform/tc-project-service/commit/81c204fc86d9f0cc2212964db68789f8251b0ed3 as we created a new script which does the same and more via https://github.com/topcoder-platform/tc-project-service/pull/546.
