### ISSUE TITLE
Changes required for project member invite update endpoint

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#277]
There are few problems with current implementation of the update endpoint of project member invite.

~~1. It does not wait for project member to be created before sending response to the caller which can be troublesome when there is an error while creating the project member object after accepting the invite. In this case, it would show success to the user while user is still not part of the project.~~ (I think I was wrong here, we are returning the promise for creating the project member [here](https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projectMemberInvites/update.js#L123) which should serve the purpose)
2. At the [line](https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projectMemberInvites/update.js#L119), we are using the request user's id to create the project member object which can create issue in a hypothetical issue when a copilot manager is approving an invite for a copilot (who was invited using email and does not exist in topcoder yet). To be safe, we should compare the email of the invite with email of the requesting user to identify if the same user is updating the invite who as invited in that invite. And we should throw an error when we are unable to find `userId`  even after this i.e. when Copilot Manager is approving the request for a non existing copilot user who was invited via email.

fyi @maxceem @gondzo @RishiRajSahu

**Comment by vikasrohit** [comment]
@maxceem @gondzo do you guys think [this](https://github.com/topcoder-platform/tc-project-service/commit/7d5f1b2212df790fb7c472cc595e4756a6ff48a8) fix would work?

**Comment by gondzo** [comment]
looks fine. 
In order to support copilot invites by email in the future we would have to call member api to get the userId from the email in the invite (case where copilot manager approves request for a copilot invited by email) - but we don't have such requirement yet, so this commit will be fine.

**Comment by vikasrohit** [comment]
I think that is already in place [here](https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projectMemberInvites/create.js#L59). This fix is to handle, when this logic of fetching id of the user by email fails, may be because user does not exist yet or there is some error in calling the API.

**Comment by maxceem** [comment]
We no longer allow inviting non-customer users by emails https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projectMemberInvites/create.js#L280-L287. 

So I guess it's safe to close this issue.
