### ISSUE TITLE
Cannot update file permission with non-admin user

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#286]
When I try to update file permissions in Connect app using a user who doesn't have admin permission, Project Service returns error: `Only admins and the user that uploaded the docs can modify`.

See demo video https://monosnap.com/file/8xlakE6v1SIQibYS1dIiQdPYZr0mm6

Can be reproduced with `pshah_copilot` and `phash_manger` users with this project https://connect.topcoder-dev.com/projects/7959 or https://connect.topcoder-dev.com/projects/7442

**Comment by vikasrohit** [comment]
@maxceem were those files uploaded by the same user who is trying to edit the file?

**Comment by maxceem** [comment]
@vikasrohit 

I think it was a client-side issue and it's fixed in the `cf16` branch. It works good now. So I'm closing this issue.

**Comment by vikasrohit** [comment]
👍
