### ISSUE TITLE
Refactor ProductTemplates to use Form instead of template property

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#288]
We already refactored `ProjectTemplate` model to keep form templates inside `Form` model.
We want to do the same for `ProductTemplate` model.

1. Make property `ProductTemplate.template` optional.
2. Add property `ProductTemplate.form` which will refer a particular form version same like `ProjectTemplate`: `{ key: String, version: Number }`
3. Create a DB migration script for changes in `ProductTemplate` model inside `/migrations` folder
4. Update `/projects/metadata?includeAllRefered` when we define `includeAllRefered` param it should also return forms which are referred in `ProductTemplates`.
5. Create a migration script similar to https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projectTemplates/upgrade.js which we can run by calling `POST /v4/projects/metadata/productTemplate/:templateId(\\d+)/upgrade`.
    The migration script would look like this:
    - if Form is not specified: create a new `Form` and copy JSON from `ProductTemplate.template` to `Form.config`
    - set `ProductTemplate.form: { key: Form.key, version: Form.version }`
    - set `ProductTemplate.template` to `null`
6. Update all unit tests, swagger and postman files according to new changes.

**Comment by maxceem** [comment]
@vikasrohit @RishiRajSahu as was mentioned by vikas here https://github.com/topcoder-platform/tc-project-service/pull/283 we should do refactoring for `productTemplates` same like we did for `projectTemplates`.

Could you please confirm that this is desired change and I'll run F2F immediately.

**Comment by RishiRajSahu** [comment]
@maxceem yeah we can launch it, but does it impact being run in parallel the execution of other backend/frontend challenges ?

**Comment by maxceem** [comment]
@RishiRajSahu this change so far is backward compatible, so it shouldn't affect other tasks in parallel.

**Comment by vikasrohit** [comment]
@maxceem I think we are done with this, right?

**Comment by maxceem** [comment]
@vikasrohit  right, it's done.
