### ISSUE TITLE
Add paused status for the milestones

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#294]
Continuing from https://github.com/appirio-tech/connect-app/issues/2968

This issue is for handling the backend changes required for the new status. We would need to keep history of the milestone status changes so that we can enable caller of the API to calculate the time spent in the each of the state of the milestone and move the status back to previous status when user wants to resume the milestone.

fyi @maxceem @RishiRajSahu

**Comment by maxceem** [comment]
@vikasrohit there is a couple of ways to go, would be great to have your view on them.

Does it make sense to make this new model universal so it could be reused by any other model not only the milestones in the future?
   1. So we can refer to the rows in this model by the `milestoneId`. In this case we can use it only for milestones. And if later we want to have the same functionality for other model we would need to create another model for that. 

      We can call model `MilestonePause`
       ```
       - id: Number, primary, autoincerement
       - milestoneId: Number (required)
       - startTime: Datatime (required)
       - endTime: Datetime
       - comment: Text (required)
       - createdBy
       - createdAt (will duplicate startTime)
       - updatedBy
       - updatedAt (will duplicate endTime)      
       ``` 
   2. Alternatively, the tracking model can refer other entities by two fields: `reference` and `referenceId`. So for the milestones `reference` would be always `milestones` and `referenceId` would be equal to the particular `milestoneId`. In such case we could reuse our tracking model for any other model by defining new `reference` values. As a disadvantage, theoretically, this tracking table could grow big if tracks pauses for too many models. Also, if we are not going to use it for any other models, this is not a necessary abstraction.

       We can call model `Pause`
       ```
       - id: Number, primary, autoincerement
       - reference: String (required)
       - referenceId: String (required)
       - startTime: Datatime (required)
       - endTime: Datetime
       - comment: Text (required)
       - createdBy
       - createdAt (will duplicate startTime)
       - updatedBy 
       - updatedAt (will duplicate endTime)
       ``` 
3. I guess we should make restictions for this model. 
    1. We can only define `startTime` when we create the records, and we cannot update `startTime`.
    2. We can only define `endTime` once. If it's already defined we cannot update it. 
    3. We can update the `comment` though.

4. If we make the restrictions above for all the users, then `createdAt` will always duplicate `startTime`. And `updatedAt` will always duplicate `endTime`. Unless admins can make changes to this model bypassing restrictions above.

**Comment by vikasrohit** [comment]
Thanks @maxceem for the updates and options. I would definitely like to make it bit generic if not fully generic. By that I mean is that we should think only about pause status for milestone (or may be a generic entity), rather we should keep history of all status changes of the target entity, some thing we are doing for project status changes already. So, my proposed schema would be:

```
- id: Number, primary, autoincerement
- milestoneId: String (required)
- status: String (required)
- comment: Text (required)
- createdBy
- createdAt (will duplicate startTime)
- updatedBy 
- updatedAt (will duplicate endTime)
```

Now, for every change in the status of the target entity, we would make an entry in this table. So, when a milestone is paused, it would have one entry with timestamp of pause as `createdAt` and later when user resumes the milestone, we would retrieve the record from this table which was previous (by order of `createdAt`) to the current `paused` status record and use the `status` from that record to move the milestone out of `paused` status. And it would cause one more entry in this table with the `status` retrieved.  Now, when we need to calculate the pause time for the milestone, we can take difference of the `createdAt` field for `paused` status record and its next(again by order of `createdAt`) record.
Also, to make this table generic, we can keep `reference` and `referenceId` instead of `milestoneId`, if we agree on that.

**Comment by maxceem** [comment]
Got the idea, thanks @vikasrohit. Just one thing to confirm. In the next comment, you are saying, that if we have milestone in pause status, we have one entry in the status table - it's clear.
After you saying:
> when user resumes the milestone, we would retrieve the record from this table which was previous (by order of createdAt) to the current paused status record and use the status from that record to move the milestone out of paused status.

Do I understand that when a user updates the status of the milestone, we should retrieve the latest status as you say, just to check if a new status is different from the previous one. And if a new status is different, then we are creating a new record in the status table. If the new status is the same like before, it means status is not changed, so we shouldn't create a new status record.

**Comment by vikasrohit** [comment]
> Do I understand that when a user updates the status of the milestone, we should retrieve the latest status as you say, just to check if a new status is different from the previous one. And if a new status is different, then we are creating a new record in the status table. If the new status is the same like before, it means status is not changed, so we shouldn't create a new status record.

Nopes, that is not the idea. I think we can easily achieve this from the front end only by not allowing user to change the status to the same status again, right?

Let me give some practical example to make it more understandable. Lets say, we have a milestone with id `123` created, so there would be following entry in the new proposed table:
```
1, 123, draft, , vikas, 2019-04-26T15:07:10, vikas, 2019-04-26T15:07:10
```
Now, lets say the milestone is moved to the `reviewed` status, now entries would be:
```
1, 123, draft, , vikas, 2019-04-26T15:07:10, vikas, 2019-04-26T15:07:10
2, 123, reviewed, , vikas, 2019-04-26T15:08:30, vikas, 2019-04-26T15:08:30
```
Now, assume that it is moved to `paused` status:
```
1, 123, draft, , vikas, 2019-04-26T15:07:10, vikas, 2019-04-26T15:07:10
2, 123, reviewed, , vikas, 2019-04-26T15:08:30, vikas, 2019-04-26T15:08:30
3, 123, paused, , vikas, 2019-04-26T15:10:30, vikas, 2019-04-26T15:10:30
```
Now, when user tries to resume the milestone, we would check from the entries above that it was in `reviewed` status before moving to the `paused` status, so we would move it to `reviewed` status when user performs a `resume` operation and now entries would be:
```
1, 123, draft, , vikas, 2019-04-26T15:07:10, vikas, 2019-04-26T15:07:10
2, 123, reviewed, , vikas, 2019-04-26T15:08:30, vikas, 2019-04-26T15:08:30
3, 123, paused, , vikas, 2019-04-26T15:10:30, vikas, 2019-04-26T15:10:30
4, 123, reviewed, , vikas, 2019-04-26T15:16:30, vikas, 2019-04-26T15:16:30
```
And total time the milestone was in paused state is the difference between `createdAt` of the last two entries i.e. `2019-04-26T15:16:30 - 2019-04-26T15:10:30` which is 6 minutes.

**Comment by maxceem** [comment]
Thanks, @vikasrohit. Got your idea.

1. As I understand, every time we change the status of milestones, we should "log" this event in the "status_history" table as you described above.
   We change milestone statuses in several ways:
   - using `create`/`update` milestone endpoints
   - when we `create`/`update` timelines, we make a cascade update of milestones of the timeline
  
   I think the best way to handle it would be using [sequalize hooks](http://docs.sequelizejs.com/manual/hooks.html) and every time when we detect changing of the milestone status, we should log this into `statusHistory`.

2. We should create additional endpoints for milestones:
     - `PATCH /v4/timelines/:timelineId(\\d+)/milestones/:milestoneId(\\d+)/status/pause` - which would move `milestone` and `phase` into the `paused` status
     - `PATCH /v4/timelines/:timelineId(\\d+)/milestones/:milestoneId(\\d+)/status/resume` - which would move `milestone` and `phase` into the previous status

**Comment by vikasrohit** [comment]
1. I am okay with sequlize hooks if they don't pose any performance issue. I checked the docs, and it says it loads all the affected records in memory to perform the hook operation. It does not seem bad to me though as we are not going to have batch operation to update the status, but still it might need some monitoring after we implement it.

2. Agreed.

**Comment by maxceem** [comment]
Thanks @vikasrohit 

It looks like we also should add some read-only [virtual column](https://sequelize-guides.netlify.com/virtual-columns/) `actualDuration` to the milestones model. Which wouldn't be stored in the DB and would be calculated as you described [above](https://github.com/topcoder-platform/tc-project-service/issues/294#issuecomment-486997090). This property should be stored in the ElasticSearch index though.

**Comment by maxceem** [comment]
@vikasrohit note, if we add a new virtual property `actualDuration` to milestones and store it in ES index, we would have to reindex ES or create some fallback code in Connect app, to support the case where we didn't have `actualDuration` yet. As for such cases `actualDuration === duration.`

**Comment by vikasrohit** [comment]
I think it would be good to have that virtual column and have it indexed in ES. Only question I have is that, how much would it cost if we don't have such field and calculate the `actualDuration` based on the actual data. I know we have to pass the `status_history` records for each milestone in our responses to milestone endpoints and I think that is the only possible thing to slow down the response, right?

> create some fallback code in Connect app

I would like to go with this rather than reindexing because we would always have `actualDuration === duration` for all milestones before the time we roll out the pause feature to the production and I would like to avoid reindexing for them. Also, logically, we can say that for the milestones where we don't have the `actualDuration` field, `duration` is the `actualDuration`. One more way just came writing the last line, we can add this logic of defaulting to `duration`, to the project service as well. Whenever we don't get any record of the milestones from status history table, we can send `actualDuration` field with value of `duration` field. Please check if it does not cause any performance cost otherwise go with the front end changes as you suggested.

**Comment by maxceem** [comment]
>  I know we have to pass the status_history records for each milestone in our responses to milestone endpoints and I think that is the only possible thing to slow down the response, right?

Right, only this. 

> One more way just came writing the last line, we can add this logic of defaulting to duration, to the project service as well.

Good idea. I don't see performance issues if we do it server-side.

**Comment by maxceem** [comment]
@vikasrohit the last thing. In this [comment](https://github.com/topcoder-platform/tc-project-service/issues/294#issuecomment-486997090) you've mentioned that we should calculate the actual time since milestone comes to the `reviewed` status. I think we should only calculate actual duration after milestone comes to the `active` status. Because `reviewed` status means that milestone is planned, but didn't start yet. And since we put milestone to `active` status, we cannot put to any other status except of `paused`. Let me know if my understanding is correct here.

**Comment by maxceem** [comment]
> One more way just came writing the last line, we can add this logic of defaulting to duration, to the project service as well.

Regarding this, I think it would be better to keep it client-side. If in the future if we reindex ES in project service, this code in project service wouldn't be used anymore. And we would forget to delete it :-). While in client side we already have a lot of code to support several backend versions, so it's ok to have such code there. Also, most likely we can make this fix fallback code in one place client side, while in project service we would need to patch several endpoints (at least 2).

**Comment by vikasrohit** [comment]
I was trying to be as much generic as we can be with ability to pause the milestone in any state. However, I think it would create confusion for now so, lets allow `paused` status only from `active` status and hence calculation of `actualDuration` would also be correct as per the understanding you shared above.
I am okay with client side as well. Go with it.

**Comment by maxceem** [comment]
@vikasrohit I've got one question regarding sending BUS events.

When we pause/resume milestones we should send `connect.action.timeline.milestone.transition.paused`/`connect.action.timeline.milestone.transition.active` events. Should we also send `connect.action.timeline.milestone.updated` in such case?

When we update milestones we send both events, if we change status.

**Comment by vikasrohit** [comment]
Yes. `connect.action.timeline.milestone.updated` is a generic event which is sent after every update in a milestone while the other two are derived/specialized events of the the raw/generic event. This is to facilitate easy consumption of such specialized events while keeping a common event which is always raised for a consumer who wants to consume every milestone update.

**Comment by maxceem** [comment]
@vikasrohit the first part of this task is done in this branch: https://github.com/topcoder-platform/tc-project-service/tree/feature/milestone-pausing
- created universal `StatusHistory` model to keep track of the status of any model
- tracking milestones status in `StatusHistory` model using hooks
- endpoints for pause/resume milestones
- sending an event to BUS API when we pause milestone

### Actual duration
We cannot store precalculated `actualDuration` in ElasticSearch. Because if currently, we are in `active` status, the `acutalDuration` should be calculated until the `current time`. But if we store it in ES, the `actualDuration` would not take into account the time which has passed since we calculated it until now.

It feels that the best way to handle it would be:
- index `StatusHistory` in ES
- when we return milestones by 
    - `GET /timelines/:tid/milestones`
    - `GET /timelines/:tid/milestones/:mid`
    - `GET /timelines/:tid`
   - we should additionally retrieve from the ES `StatusHistory` records related to the milestones we are going to return
   - populate each of returned milestone with its `statusHistory`, so milestone objects would have one more field
- as an additional hint instead of returning the whole history we can precalculare `actualDuaration` at this moment during the server response. It would mean that client side may get slightly outdated value, but I don't think we have any place where it's crucial. I think that calculating should be fast.

Let me know if have any other idea on how to handle it.

**Comment by vikasrohit** [comment]
Thanks @maxceem for the update.

> endpoints for pause/resume milestones

I am thinking of removing these endpoints now to be as much REST complaint as we can. Sorry for the confusion. I think we can reuse our existing PATCH endpoint to pause and resume the milestones with additional validation for followings:
- Milestone can not be moved to `paused` status from any other status than `active` (for now, but we should be able to easily add more statuses from which we allow moving to `paused` status`)
- When we receive status change in the PATCH request, we need to check if the milestone is already in the `paused` state right now and if it is, we should only allow status change to the status previous to the `paused` state (which I think would be tricky for a caller to identify and send in the request) or we can allow one new value (`resume`) in the `status` field and when this value is received in the payload for `status` field, we can pick the status previous to the `paused` state and update the milestone to that state. I think the later is better approach to go, still open to any suggestions.

For calculation of actual duration, I am okay with returning the complete history of the milestone status changes. I don't think a milestone would go through so many status changes that would cause the data size issues with our API response. Still, to avoid such situation in future, we can put a limit of say 10 or 20 status history records. However, while typing this response, I realized that authorization might be another issue with sending status history records to a customer, although we are pretty much sure that the requesting user is authorized to view the timeline and milestone. Let me know what do you think.

**Comment by vikasrohit** [comment]
@maxceem did you get time to analyze the pending items for this task?

**Comment by maxceem** [comment]
@vikasrohit unfortunately no. As CF took quite much time lately. But it's also on my short list.

**Comment by maxceem** [comment]
Updated code in the https://github.com/topcoder-platform/tc-project-service/tree/feature/milestone-pausing branch. Made changes to follow RESTful approach as per comment below.

> When we receive status change in the PATCH request, we need to check if the milestone is already in the paused state right now and if it is, we should only allow status change to the status previous to the paused state (which I think would be tricky for a caller to identify and send in the request) or we can allow one new value (resume) in the status field and when this value is received in the payload for status field, we can pick the status previous to the paused state and update the milestone to that state. I think the later is better approach to go, still open to any suggestions.

What is left:
- put `StatusHistory` into the ES index
- return `statusHistory` property with every `milestone` object we return in all the endpoints.

@vikasrohit is that ok to introduce a new ES index for `StatusHistory` records and call it `status_history`? For sure, we would still keep it configurable as other index names https://github.com/topcoder-platform/tc-project-service/blob/feature/milestone-pausing/config/default.json#L25

**Comment by vikasrohit** [comment]
Thanks @maxceem for the changes and apologies for the late response.
I am good with keeping the history of status changes in ES per milestone, however, I don't want to create new index for it. I would like to handle it via nested documents and in fact as we don't need to filter out milestones based on status history of that milestone, I think we can even keep them as simple array of objects in the existing `timelines` index per milestone.

**Comment by maxceem** [comment]
@vikasrohit this is completed via PR https://github.com/topcoder-platform/tc-project-service/pull/322

**Comment by maxceem** [comment]
@vikasrohit I've realized there could be some possible edge case in the current logic.

This would depend on whether we could pause/resume milestones which were created before we implemented tracking milestone status history?
- `No` - if no, everything is good, we can determine if the milestone has been created before we implemented the status history if milestone `statusHistory` propery is empty or doesn't exist.
- `Yes` - then there could be some edge case described bellow.

Imagine we have some milestone which has been created before we've implemented tracking statusHistory:
```js
milestone = {
   status: 'active',
   statusHistory: [],
}
```

After, we pause such milestone it becomes:
```js
milestone = {
   status: 'paused',
   statusHistory: [{status: 'paused', createdAt: 123, updatedAt: 123}],
}
```

Now if want to `resume` we should set the status to the previous one, but we don't know it.

There are a couple of possible solutions:
1. Create `statusHistory` records for all extent milestones with their current status. There would be two points:
    1. We would have to create many records in the DB for `statusHistory` via some migration script.
    2. We would have to reindex all the timelines with milestones.

2. Update `PATCH` ednpoint so when we `pause` some milestone we should first check if it has any `statusHistory` records. If it doesn't have such records we should create one record with the current status.

In both solution we decide which values to set for `createdAt` and `updatedAt` for these created status history records:
1. Set current values would mean that previous status last for 0 time.
2. Set them to the same as `createdAt` for milestone which would mean that milestone has been in the previous status since creation. I guess this approach would keep the algorithm to calculate the milestone duration more simple. As now we don't calculate the duration for each particular status but only calculate the total duration.

If in the future we decide to make some reports to know for each status duration separately we would have some skewed data for all these milestones as we don't have information already about status history.

**Comment by vikasrohit** [comment]
I would like to keep things simple by not allowing `pause` feature for existing milestones.

**Comment by maxceem** [comment]
> I would like to keep things simple by not allowing pause feature for existing milestones.

Ok, now I see there could be also some tricky moment.

If initially, we don't have `statusHistory` we treat this milestone old and we cannot pause it.
As soon as we change the status of a milestone, the `statusHistory` history record would be created so such milestone would become pausable.

What do you think, would be such behavior ok?

Actually, I think there is some approach to finding out if a milestone has been created before we implemented `statusHistory` or after.

We can check the `createdAt` date. When milestone is created, we set `createdAt` and at the same time create the first `statusHistory` which also set `createdAt`. There should be no difference, though we can allow some clearance we can check that difference cannot be more than 1 second.

If milestone and first `statusHistory` have almost the same `createdAt` - means that `statusHistory` has been initially created - means this milestone can be paused.
If milestone and first `statusHistory` have different`createdAt` - means that `statusHistory` has been created after the milestone - so this milestone is old and cannot be paused.

There is a very small chance that such logic can give false-positive or false-negative results.

**Comment by vikasrohit** [comment]
Logic seems good to me. However, what troubles we can get in if simply allow such milestones to be paused after first status update i.e. after first creation of status history record.

**Comment by maxceem** [comment]
> Logic seems good to me. However, what troubles we can get in if simply allow such milestones to be paused after first status update i.e. after first creation of status history record.

There would be only one thing I can see.

In the new projects, all the milestones would have a `pause` button.
But in old projects, some milestones would not have a `pause` button, because we didn't change their status yet, and some milestones would have it as soon as we updated the status of milestones. This may be confusing for users, why some milestones have the `pause` button, while others don't.

**Comment by vikasrohit** [comment]
Okay. I think that case would still be there for old milestones where the `createdAt` dates differ for milestone and statusHistory records.

I think we can leave this behaviour as is i.e. don't touch old milestones at all and let the pause button visible to the users after the first status update of the milestone. if it turns out that it is confusing to the user, we may add record, on adhoc basis, in `statusHistory` table for projects which requires pause feature for all its milestones.

**Comment by vikasrohit** [comment]
Released.
