### ISSUE TITLE
Improvements for product/project template refactoring

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#296]
This issue has the final touch which we should do for refactoring product template and project templates to use Form model.

It's a follow up from this PR https://github.com/topcoder-platform/tc-project-service/pull/290

1. In this PR helper method has been created `util.checkModel` while in previous code this method has been defined several times: 
   - https://github.com/topcoder-platform/tc-project-service/blob/feature/product-templates-refactoring/src/routes/projectTemplates/create.js#L50
   - https://github.com/topcoder-platform/tc-project-service/blob/feature/product-templates-refactoring/src/routes/projectTemplates/update.js#L53
   - https://github.com/topcoder-platform/tc-project-service/blob/feature/product-templates-refactoring/src/routes/projectTemplates/upgrade.js#L55
   
   So we can reuse a new helper method in all these cases.

2. At the moment we have two ways of defining forms for both `ProductTemplates` and `ProjectTemplates`: old way inside the template and new way using Form model. 
    So both of fields are optional:

     ![image](https://user-images.githubusercontent.com/146016/56023691-0767a080-5d41-11e9-9aee-bf624ff0b3eb.png)

    and
    
    ![image](https://user-images.githubusercontent.com/146016/56023879-75ac6300-5d41-11e9-9d6e-e5b21538e28e.png)

    For `ProductTemplate` we should check in create/update endpoints that 
    - either `form` or `template` field is defined, but not both together.

    For `ProjectTemplate` we should check in create/update endpoints that:
    - either `scope` or `form` field must be defined, but not both together
    - `scope` or `priceConfig` cannot be defined together (they can be both `null` though)
    - either `phases` or `phaseConfig` field must be defined, but not both together.

**Comment by mfikria** [comment]
@maxceem resolved in https://github.com/topcoder-platform/tc-project-service/pull/297

**Comment by maxceem** [comment]
@vikasrohit just in case, this is already done and merged to DEV.
