### ISSUE TITLE
New endpoints for fetching project phases and products from database

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#299]
Currently we have list endpoint for fetching a project's phases/products which fetches the data from ES cluster. There are incidents where we are not able to get the phases/products in time for a project just after creating a project. So get rid of that situation, we need to have an endpoint which returns data from database without waiting for ES indexing.
Purpose of this task is to replicate the behaviour of current list endpoints for `projectPhases` and `phaseProducts` and use database instead of ES index to fetch the data from.

**Comment by maxceem** [comment]
@vikasrohit to confirm.

Currently, we have endpoints 
- to list phases `GET /v4/projects/:projectId(\\d+)/phases` https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/phases/list.js
- and products `GET /v4/projects/:projectId(\\d+)/phases/:phaseId(\\d+)/products` https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/phaseProducts/list.js

We should implement endpoints to get data from DB for them
- `GET /v4/projects/:projectId(\\d+)/phases/db`
- `GET /v4/projects/:projectId(\\d+)/phases/:phaseId(\\d+)/products/db`

This should be done a similar way as now its done for projects:
- https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projects/list-db.js

**Comment by vikasrohit** [comment]
Yes.

**Comment by maxceem** [comment]
@vikasrohit just in case, this is already done and merged to DEV branch.
