### ISSUE TITLE
[$35] Prevent non admins to update the template id of a project

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#314]
As of now a customer can update the template id of their projects by directly calling the API endpoint. Although, it does not do any harm but it can result in issues in rendering a project because data for the project would not be stored in the formatted as per the updated templated id.
So, we should prevent updating template id of an existing project for non admin users.

fyi @maxceem @RishiRajSahu

**Comment by maxceem** [comment]
We should update the existent unit test after this fix. And also, we should create 2 new unit tests to check that:
- admin user can update `templateId`
- non-admin user cannot update `templateId `and got error `403` - `You don't have permission to change project template`.

**Comment by gets0ul** [comment]
Is this different with connect-app bug bash?  
Can I work on this?

**Comment by maxceem** [comment]
It's the same Bug Bash with Connect app. You can work no this, but you can work only at one issue at a time. So you should complete https://github.com/appirio-tech/connect-app/issues/3112 first, or unassign that one first.

**Comment by r0hit-gupta** [comment]
I would like to work on this.

**Comment by maxceem** [comment]
@r0hit-gupta assigned.

**Comment by r0hit-gupta** [comment]
@maxceem its already ignoring the template Id. https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projects/update.js#L65

**Comment by maxceem** [comment]
Thanks, @r0hit-gupta. Please, hold on this until I confirm if we should let admins to update it.

@vikasrohit currently, we cannot update `templateId` should we let admins to do it?

**Comment by maxceem** [comment]
@r0hit-gupta as we are on hold for this one, you may pick up another one, if you want to https://github.com/topcoder-platform/tc-project-service/issues/323

**Comment by romitgit** [comment]
@maxceem Is this availables to pick up. If yes, please assign to me

**Comment by maxceem** [comment]
@romitgit we are waiting for clarifications for this issue. At the moment it's not available for pick up.

**Comment by vikasrohit** [comment]
@maxceem @r0hit-gupta Yep, I think I missed that and I think I didn't checked it via calling the API endpoint. However, when we are here, can we do following thing for the sake of considering this issue  a valid task (may be with reduced prize money):

Verify that if we have unit test for the same case i.e. no one should be able to update the templateId via API directly. If we don't, lets add unit tests for this case. If we already have unit tests, lets close this task.

**Comment by r0hit-gupta** [comment]
Yes, sure. Working on it.

**Comment by maxceem** [comment]
Ok @vikasrohit, so for this issue, we have to add a unit test that admin user cannot update `templateId`. I guess as per current logic it's enough to to check for admins, thinking that other users have less permissions and also cannot update it.

The prize for this issue is reduced to $25.

fyi @r0hit-gupta

**Comment by vikasrohit** [comment]
@maxceem I would like to have 3 separate unit tests for, one for admins, another for copilots and last for customers (Topcoder User).

**Comment by maxceem** [comment]
Ok @vikasrohit. @r0hit-gupta I've slightly increased the prize for 3 tests.

**Comment by r0hit-gupta** [comment]
@maxceem @vikasrohit currently the code ignores the templateId and returns a status of 200 even if we send a different template Id. What should be done for the tests?

**Comment by maxceem** [comment]
@r0hit-gupta validate inside tests that the value of `templateId` is not updated, even though we try to update it in the request body.

**Comment by r0hit-gupta** [comment]
PR #335

**Comment by maxceem** [comment]
@r0hit-gupta I've reviewed your PR, please have a look https://github.com/topcoder-platform/tc-project-service/pull/335#pullrequestreview-258774305

**Comment by r0hit-gupta** [comment]
Feedback addressed. Please review.

**Comment by maxceem** [comment]
Hi @r0hit-gupta, please let me know your Topcoder handle to process the payment for this issue.

Thanks.

**Comment by r0hit-gupta** [comment]
Its [rohitgupta_](https://www.topcoder.com/members/rohitgupta_)

**Comment by vikasrohit** [comment]
Released.
