### ISSUE TITLE
New data models for work management

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#315]
We need to introduce new data models and need to update existing ones to achieve the requirements/features needed for the new work management strategy. Though, we don't have final designs of all input and display requirements, we do have the feature details and we can determine common fields out of those details. So, we can start creating the model and API endpoints around it to be ahead of time and later update the end points when we have more detailed UI designs.

Technically, there is one new data model called `WorkStream` that is going to be introduced and it would have schema like:

```
id bigint,
name varchar(255),
type varchar(45) or enum (dev, qa, design, deploy),
status enum (draft, reviewed, active, paused, completed), // we might not need this in final version
projectId bigint,
createdAt timestamp,
updatedAt timestamp,
createdBy bigint,
updatedBy bigint,
deletedAt timestamp,
deletedBy bigint
```
New endpoints:
```
GET /projects/{projectId}/workstreams (fetch directly from database)
GET /projects/{projectId}/workstreams/{id} (fetch directly from database)
POST  /projects/{projectId}/workstreams (only admins should be able to directly create the workstreams)
PATCH  /projects/{projectId}/workstreams/{id} (it requires complex logic of authorization depending on the project template, for some templates we allow customers to be able to update the details while for others we don't)
DELETE  /projects/{projectId}/workstreams/{id} (only admins should be able to directly deleted the workstreams)
```

We need to keep one to many relationship (via cross ref table) between `WorkStream` and `Phase` object so that one work stream can have multiple phases. `Phase` object would remain mostly as is. For old projects a phase won't be associated with any work stream, so it is not mandatory for a phase to have workstream associate with it. After we have this relationship, following new endpoints are needed:

```
GET /projects/{id}/workstreams/{id}/works (we are calling a phase as work in new terminology without changing it in our data model. fetch phases from the database directly.)
GET /projects/{id}/workstreams/{id}/works/{id} (fetch directly from database)
POST  /projects/{id}/workstreams/{id}/works (it requires complex logic of authorization depending on the project template, for some templates we allow customers to be able to create work for a worksstream while for others we don't)
PATCH  /projects/{id}/workstreams/{id}/works/{id} (it requires complex logic of authorization depending on the project template, for some templates we allow customers to be able to update the details of a work while for others we don't)
DELETE  /projects/{id}/workstreams/{id}/works/{id} (it requires complex logic of authorization depending on the project template, for some templates we allow customers to be able to delete a work while for others we don't)
```

**Note** We would still keep our existing endpoint of `/projects/{id}/phases` and all its child routes as is. These endpoints would serve the response for old projects as is while for new projects, which have workstreams, these endpoints would allow us to interact with all `work` for the project e.g. `GET /projects/{id}/phases` would return all the phases in the project no matter which workstream they are associated with. There would be no mention of `workstream` or `work` in the request or response for new projects when accessed via this old endpoints. I don't see any usage of these endpoint as of now, but for completeness and backward compatibility, we need to ensure this behaviour.

Now, next change in data model is to now utilize the one to many relationship between a `Phase` and `PhaseProduct` to capture the new details about associating a phase/work with challenge/task. Our idea is to keep `PhaseProduct` as object to keep details about a challenge/task associated with a phase. I guess, until we have final UI requirements get started, we can use this model as is and keep any details (e.g. challenge id, type, etc in `details` field of `PhaseProduct`). We might need to update the schema though as soon as we get more requirements around challenges/tasks association.
However, we would need new endpoints for serving `PhaseProduct` for new projects as follows:

```
GET /projects/{id}/workstreams/{id}/work{id}/workitems (fetch directly from database)
GET /projects/{id}/workstreams/{id}/work{id}/workitems/{id} (fetch directly from database)
POST /projects/{id}/workstreams/{id}/work{id}/workitems (it requires complex logic of authorization depending on the project template, for some templates we allow customers to be able to create work items for a worksstream while for others we don't)
PATCH /projects/{id}/workstreams/{id}/work{id}/workitems/{id} (it requires complex logic of authorization depending on the project template, for some templates we allow customers to be able to update the details of a work item while for others we don't)
DELETE /projects/{id}/workstreams/{id}/work{id}/workitems/{id} (it requires complex logic of authorization depending on the project template, for some templates we allow customers to be able to delete a work item while for others we don't)
```

**Comment by maxceem** [comment]
@vikasrohit, in general, it looks clear.

Have a few questions to make sure I've got everything right.

1. > We need to keep one to many relationship (via cross ref table) between WorkStream and Phase object 

   Do you mean that we have to create an additional model to implement this relation? Or just add one more field to the `Phase` model: `workstreamId` which would refer to a `WorkStream` or can be `null`.

2. Regarding `/projects/{id}/phases` endpoints:
     > I don't see any usage of these endpoint as of now, but for completeness and backward compatibility, we need to ensure this behaviour.

   As I understand we keep them as they are now. And they should ignore that some of the phases would be related to some WorkStreams after adding such relation.

3. Regarding `PhaseProduct` as I understand so far we don't make changes to the model. And we use the existent relation between `Phase` and `PhaseProduct` which is done via JSON in `details` at the moment.

**Comment by vikasrohit** [comment]
> Do you mean that we have to create an additional model to implement this relation? Or just add one more field to the Phase model: workstreamId which would refer to a WorkStream or can be null.

I would not like to add any reference of workstream directly to the phase, rather I am thinking of using a join table to maintain this relationship which I guess is supported only via `belongsToMany` association in sequelize. I am still open for the way you suggested, if we see any issues with the way I proposed.

> As I understand we keep them as they are now. And they should ignore that some of the phases would be related to some WorkStreams after adding such relation.

Yes, I think we don't need to make any change to the code for this endpoint. However, we might need to verify that this works after we introduce the models. 😬 

> And we use the existent relation between Phase and PhaseProduct which is done via JSON in details at the moment.

Yes, we are going to use existing relation but it is not maintained via `details` JSON, we already have `phaseId` field in `phaseProduct` model. `details` is just used to store the requirements of the specific `phaseProduct` which is rendered as the `Specification` tab of a phase.

**Comment by maxceem** [comment]
> I would not like to add any reference of workstream directly to the phase, rather I am thinking of using a join table to maintain this relationship which I guess is supported only via belongsToMany association in sequelize. I am still open for the way you suggested, if we see any issues with the way I proposed.

Ok. So we will add one more model `PhaseWorkStream`:
```SQL
-- phase_work_stream table

phaseId bigint NOT NULL,
workStreamId bigint NOT NULL,
```
And use sequalize feature `belongsToMany`: 
```js
Phase.belongsToMany(WorkStream, { through: PhaseWorkStream })
```
> Yes, we are going to use existing relation but it is not maintained via details JSON, we already have phaseId field in phaseProduct model

Hmm, strange that we don't have `phaseId` in sequalize model of the `PhaseProduct` https://github.com/topcoder-platform/tc-project-service/blob/dev/src/models/phaseProduct.js#L3-L20 but we have it in SQL migration script https://github.com/topcoder-platform/tc-project-service/blob/dev/migrations/20180608_project_add_templateId_and_new_tables.sql#L89
I guess we should add it to the sequalize model too.

**Comment by vikasrohit** [comment]
> Phase.belongsToMany(WorkStream, { through: PhaseWorkStream })

Do we need 

```
WorkStream.belongsToMany(Phase, { through: PhaseWorkStream })
```
as well? or can we just specify only one of these (preferably the one I suggested above) to fulfill all the requirements of specifying the association? 

> I guess we should add it to the sequalize model too.

We don't need that as it added by association specified by https://github.com/topcoder-platform/tc-project-service/blob/dev/src/models/projectPhase.js#L42

**Comment by maxceem** [comment]
> Do we need

> WorkStream.belongsToMany(Phase, { through: PhaseWorkStream })
> as well? or can we just specify only one of these (preferably the one I suggested above) to fulfill all the requirements of specifying the association?

Do you mean that we don't have to explicitly create the model `PhaseWorkStream` as we are not going to add any additional fields to the joint table, and we can do like:
```js
WorkStream.belongsToMany(Phase, { through: 'PhaseWorkStream' }) // 'PhaseWorkStream' is a string
```
And, create an SQL migration script for creating according table in the DB:
```SQL
-- table
-- phase_work_stream
phaseId bigint NOT NULL,
workStreamId bigint NOT NULL,
```

Or did you mean some other way? As I don't see another way at the moment from your input.

**Comment by vikasrohit** [comment]
Yep, having relationship between Phase and WorkStream, without creating the model is also something I would like to have as Sequelize support that.

However, my intention is the last comment is about keeping the relationship between these two entities from `WorkStream` object instead of `Phase` i.e. 
using `WorkStream.belongsToMany(Phase, { through: 'PhaseWorkStream' })` instead of `Phase.belongsToMany(WorkStream, { through: PhaseWorkStream })` because the later one says one phase belongs to many workstreams which actually not the case and we are just doing this for keeping the relationship in separate table while in the former one we are saying that a workstream belongs to multiple phases. Another question is that, do we need to specify relationship in both ways to fulfill the requirements of Sequelize to maintain many to many relationships.

**Comment by maxceem** [comment]
Hmm. So the concern is `WorkStream.belongsToMany(Phase, { through: 'WorkStreamPhase' })` vs `Phase.belongsToMany(WorkStream, { through: PhaseWorkStream })`.

As per my understanding in our case, the next endpoint `/projects/{id}/workstreams/{id}` should return a list of `Phase` which belongs to one `WorkStream`. This is equivalent of `Phase` model to have `workStreamId`, which we would replace with a join table and `belongsToMany`.
It feels for me that this is equivalent to `Phase.belongsToMany(WorkStream, { through: PhaseWorkStream })`. Though I didn't find an example for such case, as the main purpose for `belongsToMany` is to handle `N:M` relations, while in our case we have `1:M` relation which is usually handled by the foreign keys.

For our case, it feels that `belongsTo`/`hasMany` pair would be more suitable  (see [example](http://docs.sequelizejs.com/class/lib/associations/base.js~Association.html)), but it uses a foreign key instead of a join table.

Maybe I'm missing some point here, let me know if you got where is the confusion.

**Comment by vikasrohit** [comment]
> As per my understanding in our case, the next endpoint /projects/{id}/workstreams/{id} should return a list of Phase which belongs to one WorkStream

I guess you meant `/projects/{id}/workstreams/{id}/**works**` and my point is that one workstream can have more than one phases but one phase would never belong to multiple workstreams.

**Comment by maxceem** [comment]
Thanks, @vikasrohit you are right. I was a little bit mixed up here.

The requirements are clear for me now. Just to get a wider perspective, what is the main intention to use a join table here instead of a foreign key `workStreamId` inside `Phase` model? Are there any future plans connected with these tables?

**Comment by vikasrohit** [comment]
I am just trying to keep the workstream logic separate from phases because I have seen the terminology changing very significantly over the time (e.g. now we are calling `phase` as `work`, which had as naming convention in Connect v1 😬)

**Comment by maxceem** [comment]
@vikasrohit the last questions here before I lunch it:

1. There are few endpoints which require complex logic of authorization depending on the project template, for some templates we allow customers to be able to update the details while for others we don't. 
   1. Do we have any details regarding this requirement? Or should we let all customers to perform these actions at the moment?
   2. This would be NOT allowed to `copilots` in any conditions right?

2. All the `GET` endpoints can be accessed by any **authenticated user** who is **a member of a project** + **admin users**, correct?

**Comment by vikasrohit** [comment]
1. We can not determine any specific logic for customer access. I mean, we need to be generic in terms of having capability of controlling access of work management based on user roles and project template. May be we can ask participants to improvise there.

2. I can not think case where your statement does not hold true, so we should be good for now.

**Comment by maxceem** [comment]
> capability of controlling access of work management based on user roles and project template

if permissions only depend on `user roles` and `template` I think we can add a `metadata` field to the `projectTemplate` model. And use it to define the list of user roles which can edit works for this template, something like this:
```
projectTemplate = {
   metadata: {
      workManagementRoles: ['Copilot', 'Topcoder User']
   }
}
```
In the future we can define some additional data in`metadata` for templates if we need.

#### Very general approach

There could be another more general approach. If we have any plans to use some custom access logic for other endpoints. Maybe we can think about some very general approach which would let use define permission for any endpoint using some rules. I guess this would require us to introduce some new model. This is just a vague idea.

**Comment by vikasrohit** [comment]
Yes, I guess most probably it would be a combination of `userRoles` and `projectTemplate`, however, there might be multiple types of actions that can be controlled via these permissions e.g. `customer` role users might be allowed to create/update/delete work cards for a particular `projectTemplate` while `copilot` role users might be allowed only to attach challenges/tasks to the existing work cards for the same project template. So, inspiring from your both approaches, can we use something similar to following table schema:

```
CREATE TABLE work_management_permissions
(
    id bigint NOT NULL,
    action varchar(255), // e.g. 'CRUD_WORK' for managing access to the CRUD operations on Work
    allowedRoles array(varchar),
    deniedRoles array(varchar),
    "projectTemplateId" bigint NOT NULL,
    "deletedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    "deletedBy" bigint,
    "createdBy" integer NOT NULL,
    "updatedBy" integer NOT NULL,
    CONSTRAINT work_management_permissions_pkey PRIMARY KEY (id)
);
```

**Comment by maxceem** [comment]
1. Do I understand it right, that your suggestion is to add more values to `action` in the future for special cases like for "copilot role users might be allowed only to attach challenges/tasks to the existing work cards"?
 
   While in the beginning, we can have two supported values for `action`:
   - `CRUD_WORK` to manage permissions for `POST/PATCH/DELETE /projects/{id}/workstreams/{id}/work{id}/workitems` endpoints
   - `CRUD_WORKSTREAM` to manage permission for  `POST/PATCH/DELETE /projects/{id}/workstreams/{id}/works` endpoints

2. Should we use values like `C_WORK`/`U_WORK`/`D_WORK` and combinations like `UD_WORK`?To control particular actions permissions?

3. Do you see any usage example for `deniedRoles`? I was thinking that by default users would not be allowed to perform the actions unless there is a rule to allow.

4. We would only apply these rule checks for `POST/PATCH/DELETE` endpoints, but not to `GET` right?

**Comment by vikasrohit** [comment]
1. Yes, we can mode values as you suggested e.g. `CRUD_WORK`, `CRUD_WORKSTREAM` etc

2. Theoretically, we can do that if we need that, however, for now we only need to control all write operations as single permission i.e. allowed role would be able to create/edit/delete the entity.

3. Its more like standard Access Control Lists in operating systems, just to have the facility of denying specific role from certain action so that a user with a super set role could be denied permission on certain action to avoid confusion e.g. for  a user who has  Connect Manager and Account Manager roles, we might want to limit the access to manage the work cards as we assume that a person having Account Manager role has more specific duties and we don't want to confuse them with more options. We would still have the option to let it behave normally by leaving the `deniedRoles` empty.

4. Yep, for now we don't need limit `GET` operations for work endpoints as every one in the project can see them if they are available. So, essentially for now the `action` can be `CUD_WORK`

**Comment by maxceem** [comment]
I'd like to extend the first question regarding:

> copilot role users might be allowed only to attach challenges/tasks to the existing work cards

It looks like permissions could be quite specific. I mean not only just let users to call `POST/PATCH/DELETE` but also permission to `PATCH` the model in some specific way, is that correct? And we don't have yet more detailed requirements here.

So this means, that most likely we would have to hardcode the rules for other values of `action` inside endpoints, as logic might be complicated, require retrieving existent data. So this leads to the fact, that we cannot create a middleware for this purpose I guess. And every endpoint would have to use data from the `work_management_permissions` model directly.

**Comment by vikasrohit** [comment]
Okay, got it where the confusion is.

I don't think we would like to control the permission to an endpoint in some specific way, although having this support would be great. 😬 I don't think we have that requirement as of now, all we need is to stop users without proper roles to managing the work objects.

I think, we can have a single middleware which can be aware of all types `action` in `work_management_permissions ` and control the access to the endpoints either by hardcoding the mapping between the `action` and the actual endpoint `URL` and `HTTP_METHOD` OR we can have `URL` and `HTTP_METHOD` in the table as columns as well. It is same as you were suggesting in your very general approach above.

**Comment by maxceem** [comment]
Thanks, @vikasrohit now the task regarding permissions is clear.

I think we can reuse [permissions](https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projects/create.js#L216) middleware same way we use it for other endpoints.

1. For each of new endpoint we would use `permissions` as usual like:
    ```js
    permissions('workStream.edit')
    permissions('workItem.delete')
    // and so on
    ```

2. We would setPolicy as for [other ednpoints](https://github.com/topcoder-platform/tc-project-service/blob/dev/src/permissions/index.js#L18):
     ```js
     Authorizer.setPolicy('workStream.create', projectAdmin); // same like for project admins
     Authorizer.setPolicy('workStream.edit', workManagementForTemplate); // handler which will check permissinos based on the tamplete
     Authorizer.setPolicy('workStream.delete', workManagementForTemplate); // handler which will check permissinos based on the tamplete
     Authorizer.setPolicy('workStream.view', projectView); // same like view project
     ```

3. `workManagementForTemplate` handler would retrieve `project` and determine `templateId`. After that, it would use the policy name (`workStream.edit`) to retrieve permissions rules from the next table:

    ```
    CREATE TABLE work_management_permissions
    (
        id bigint NOT NULL,
        policy varchar(255) NOT NULL, // e.g. 'workStream.edit',
        allowRule json NOT NULL,
        denieRule json,
        "projectTemplateId" bigint NOT NULL,
        "deletedAt" timestamp with time zone,
        "createdAt" timestamp with time zone,
        "updatedAt" timestamp with time zone,
        "deletedBy" bigint,
        "createdBy" integer NOT NULL,
        "updatedBy" integer NOT NULL,
        CONSTRAINT work_management_permissions_pkey PRIMARY KEY (id)
    );
    ```

    1. We can make a combination of (policy + projectTemplateId) unique.
    2. So I propose to use `policy` field instead of `action`, `URL` and `HTTP_METHOD` to follow our current approach. If later we would need some more specific rules, we may think about other approaches when we have particular requirements.
    3. Also, I propose to replace `allowedRoles` and `deniedRoles` with more common `allowRule` and `denieRule` which would have the same format as we started using in Connect app, [see](https://github.com/appirio-tech/connect-app/blob/dev/src/config/permissions.js#L11).
      ```js
      allowRule: { 
        projectRoles: ['customer', 'manager'],
        topcoderRoles: ['Connect Admin', 'administrator']
      },
      denieRule: { 
        topcoderRoles: ['Connect Account Manager']
      }
      ```
      This way we control permission rules more precisely. In particular, we can require that only `Connect Manager` who is a member of the project with a `manager` role can have access, rather than just any `Connect Manager`. Also, this way we would go for the unified way of defining permissions between Connect and Project Service.
    4. If for some template `work_management_permissions` record is not found, should we treat like permission is granted or user doesn't have permission?

4. I guess we should decide on how we would manage these permissions. As they suppose to be defined per projectTemplates, so it's not easy to create them manually by making DB queries. Should we add endpoints to manage data in `work_management_permissions` table? So later we can add UI in our metadata editor to set permissions per projectTemplate?

**Comment by vikasrohit** [comment]
I liked the idea @maxceem and I think we should be good with that. One thing I am slightly confused is the use case which mentioned as `In particular, we can require that only Connect Manager who is a member of the project with a manager role can have access, rather than just any Connect Manager.`. I think `projectRoles` and `topcoderRoles` in the rules are `ORed` not `ANDed`. So, I am not sure how would we achieve that use case (to be clear, we won't exactly such case though but we might have similar one as I mentioned [previously](https://github.com/topcoder-platform/tc-project-service/issues/315#issuecomment-503057664) in this thread)

> If for some template work_management_permissions record is not found, should we treat like permission is granted or user doesn't have permission?

We should deny the access this permission table would be applicable only for work management and work management would be enabled only for new project templates for whom we would add the entries for sure. And any old project template which is not supposed to have work management features, would be denied to access these endpoints however, they would still be able to access the old `phases` endpoints to manage their delivery.

> I guess we should decide on how we would manage these permissions. 
Yes, we need to, however, I don't want to invest much time in their as we are not sure how much things can get complicate in terms of these work management permissions. It might be the only use case to restrict CUD operations on the work cards per template. In that case it might not make sense for us to invest in that direction as of now.
Ideally, yes we should get that moved to metadata UI and endpoints. If we can run these efforts in parallel without any impact on our main feature of work management and its access control, we might think to start on it as well.

**Comment by maxceem** [comment]
> One thing I am slightly confused is the use case which mentioned as In particular, we can require that only Connect Manager who is a member of the project with a manager role can have access, rather than just any Connect Manager.

What I meant here is that the next rule let any `Connect Manager` to access:
```js
allowRule: { 
  topcoderRoles: ['Connect Manager']
},
```
while the next rule, let only access to users who joined the project with a `manager` role:
```js
allowRule: { 
  projectRoles: ['manager'],
},
```

> I guess we should decide on how we would manage these permissions.

So to keep it simple at the moment we wouldn't create API to manage `work_management_permissions` and would populate it directly via SQL commands. Do you think that would be enough for now?

**Comment by vikasrohit** [comment]
Sorry @maxceem Missed to reply here. I am good with your observations.

**Comment by maxceem** [comment]
@vikasrohit during testing of Workstreams model I've discovered that one thing which maybe we can revise a little bit.

Actions for some endpoints we control by getting permission records for particular templates from  `work_management_permissions`. So until we create these permission records in the `work_management_permissions` we cannot to do some actions. And this should be done for every project template which we want to use.

Should we have some default permission so at least admins can make these actions?

**Comment by vikasrohit** [comment]
I would like to have that explicitly. I mean, we should be consciously making either API calls or run SQL scripts to enable the work management for a particular template. We might add this feature in the meta data management UI in future.

For now, are you suggesting to add default permissions to admin by a script or by having a exception code block which allows admin for every operation?

**Comment by maxceem** [comment]
> For now, are you suggesting to add default permissions to admin by a script or by having a exception code block which allows admin for every operation?

I wasn't sure about the approach here, just noticed that testing this functionality is quite tedious and time-consuming.

As per your input, I guess we can create some helper CLI script or API endpoint which we can use to add some default permissions to some particular template. So we can use at least during development. Or maybe even for production later. 

Which way would you prefer?

**Comment by vikasrohit** [comment]
I would like to go for API endpoint instead of CLI script.

However, I think the easiest solution for us is to have exception in code for admins as we are doing at many other places in our code.

**Comment by maxceem** [comment]
@vikasrohit I've just realized that apart from the ability to create permissions, we should have the ability to edit them. So probably we should create the whole set of endpoints to manage `workManagementPermission`.

Note, as a temporary solution to continue running challenges I've created a fallback so if there is not permission defined, we use default permission and all topcoder managers can do any action with works https://github.com/topcoder-platform/tc-project-service/blob/dev/src/permissions/workManagementForTemplate.js#L39-L45.

If you think that's ok for now, we keep it like that until we understand our cases to grant permissions more precisely. So we can wait to implement API for permission. Or if you already know the cases, we can implement API.

**Comment by vikasrohit** [comment]
I think the default permission is the only way to save some time for us right now. We should not waste our time in this release for developing the permissions APIs and may UI for it, unless we are blocked without implementing it.

**Comment by vikasrohit** [comment]
@maxceem can we close this one now?

**Comment by maxceem** [comment]
yes, totally.
