### ISSUE TITLE
[$100] Make sure transactions work automatically

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#323]
As we use `continuation-local-storage` for `Sequelize` transactions should work without direct passing the `transaction` object into the `options`. And we use this in many places in the project:

![image](https://user-images.githubusercontent.com/146016/60326099-7efdb100-99bb-11e9-830c-70e06a0f2881.png)

Though as per my testings, it feels that transactions didn't work (partials changes weren't reverted in case something failed). But it might be some other reasons as I could make several fixes at once as I was sure that it wouldn't work without directly defining transactions. So as a result in new changes done in this PR https://github.com/topcoder-platform/tc-project-service/pull/322 I forced passing transactions explicitly:

![image](https://user-images.githubusercontent.com/146016/60326177-b0767c80-99bb-11e9-9bba-64dd4e4f98b5.png)

### Todo
1. Make sure that transactions work without explicit passing as we are using `continuation-local-storage` for `Sequelize`, see [docs](http://docs.sequelizejs.com/manual/transactions.html).

2. Update code to NOT pass transactions explicitly.

**Comment by maxceem** [comment]
For the first part we should verify if transactions work or no automatically if we don't define `tx` explicitly. After we get results of this verification part we would decide what to do next.

1. Update code to not pass transactions directly in the cases when we pass it now.
2. `Test case 1`. When we update milestone status using `PATCH /v4/timelines/:timelineId(\\d+)/milestones/:milestoneId(\\d+)` we always create `statusHistory` records to track the status of milestones. We should make sure that if the transaction failed and we didn't manage to complete update fully, the `milestone` is not updated and `statusHistory` record is not created.

    `throw` error somewhere in the code **after** `milestone` is updated and `statusHistory` record is created inside the transaction. Check that after such error all the object from the transactions was not updated/created in the DB.
3. `Test case 2`. We have another endpoint which has a bigger and more complex transaction to test `POST /v4/timelines`.
    If we create a timeline with defined `templateId`, it would trigger creating the list of milestones for the template using `bulkCreate` https://github.com/topcoder-platform/tc-project-service/blob/feature/milestone-pausing/src/routes/timelines/create.js#L61-L109

    So for testig, we can create a timeline with the body like the next one:
    ```js
    {
      "param":{
        "name":"new name",
        "description":"new description",
        "startDate":"2018-05-29T00:00:00.000Z",
        "endDate": "2018-05-30T00:00:00.000Z",
        "reference": "project",
        "referenceId": 1,
        "templateId": 29
      }
    }
    ```

     Make sure that you put to `referenceId` some existent `projects.id`. And to `templateId` some existent `milestone_templates.referenceId`.

     To have some demo data in the DB use the next command from the readme, so you don't have to create templates and project manually: https://github.com/topcoder-platform/tc-project-service#import-sample-metadata--projects

     `throw` error somewhere in the code after `timeline`, `milestones` and `statusHistory` records are created inside the transaction. Check that after such error all the object from the transactions was not created in the DB.
4. Create 2 demo videos which would demonstrate how `Test case 1` and `Test case 2` behave: do transaction works after removing `tx` or no? Provide links to the demo videos.

**Comment by mhikeo** [comment]
Hi. Kondly assign this to me. Thanks.

**Comment by maxceem** [comment]
@mhikeo assigned.

**Comment by maxceem** [comment]
As no comment has been provided during 12 hours as per this [Bug Bash](https://www.topcoder.com/challenges/30095031 rules), this issue is now open for pickup.

**Comment by r0hit-gupta** [comment]
Please assign me.

**Comment by maxceem** [comment]
@r0hit-gupta assigned.

**Comment by maxceem** [comment]
Hi @r0hit-gupta, please, let me know if you are working on it, or I'll open it for everyone to pick up.

**Comment by r0hit-gupta** [comment]
Unable to solve. Please open it up for others.

**Comment by maxceem** [comment]
Thank you for update @r0hit-gupta .

This issue is now open for pick up.

**Comment by gurmeetb** [comment]
@maxceem let me give a try, please assign me.

**Comment by maxceem** [comment]
Assigned @gurmeetb

**Comment by gurmeetb** [comment]
Thanks @maxceem - can you also plz give me access to repo, not able to clone it? 

`Please make sure you have the correct access rights and the repository exists.`

**Comment by maxceem** [comment]
The repo is public. How do you clone it?
Try using the HTTPS link https://github.com/topcoder-platform/tc-project-service.git

**Comment by gurmeetb** [comment]
> The repo is public. How do you clone it?
> Try using the HTTPS link https://github.com/topcoder-platform/tc-project-service.git

Kindly ignore, this was my bad, was using wrong rsa/pwd combo. Thanks, I am able to clone now.

**Comment by gurmeetb** [comment]
@maxceem had not been able to setup env still using v8.2.1, please open it up for others.

**Comment by gets0ul** [comment]
Please assign me.

**Comment by maxceem** [comment]
Thank you for letting me know @gurmeetb.

Assigned to you @gets0ul.

**Comment by gets0ul** [comment]
PR: https://github.com/topcoder-platform/tc-project-service/pull/337  

Videos:
Create timeline
https://drive.google.com/file/d/1_RXlvfLyHQQADedNSBywtN7DH8WhtP2O/view?usp=sharing

Update milestone
https://drive.google.com/file/d/10ZushV7bs3iz0K-CkWw59ebJhlxYjuv_/view?usp=sharing

**Comment by maxceem** [comment]
@vikasrohit FYI transactions work good without defining them explicitly. So we remove any usage of explicit transactions in the PR https://github.com/topcoder-platform/tc-project-service/pull/337 and it could be merged later together with other CF tasks.

**Comment by vikasrohit** [comment]
Released
