### ISSUE TITLE
New Project Submission Status

### ISSUE THREAD

**Issue by parthshah** [topcoder-platform/tc-project-service#33]
We need the ability to have new projects that are submitted start in a status where only operations can view them. 

This will allow us to:
~ Validate the project before a copilot is assigned
~ Directly assign to a copilot (in special cases)
~ Make powered by teams aware of the project
~ Delete or remove test or junk projects

**Comment by parthshah** [comment]
@fnisen - is this still valid?

**Comment by fnisen** [comment]
@parthshah where is this issue coming from? Is this an old one from Asana? I can't find the original source. 

I don't think this is valid anymore. We fixed it by introducing the "In Review" status in Project v4.

**Comment by parthshah** [comment]
Yep, it's an old issue that was logged in Asana.
