### ISSUE TITLE
[$150] Fix copilotAndAbove permission to check that users is a member of the project

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#332]
From @vikasrohit 
> API for adding phases to a project endpoint does not validate if the caller is a member of the project or not. So, a copilot of one project can add phases to any other project in Connect. I am not sure if this is the case with other phase or other entities options as well.

I see that permission `copilotAndAbove` doesn't check if the user is a member of a project or no, only user role of Topcoder, see https://github.com/topcoder-platform/tc-project-service/blob/challenge%2F30095006/src/permissions/copilotAndAbove.js#L11

This rule is used for all the CRUD endpoints for phases and products, see https://github.com/topcoder-platform/tc-project-service/blob/challenge%2F30095006/src/permissions/index.js#L43-L48

@vikasrohit 
1. Should managers only be able to update projects which are they member of or no?

**Comment by vikasrohit** [comment]
`Connect Manager` s should also be restricted to add phases to the projects they are part of. They can always join the project at their will, but this restriction would prevent any accidental modification of the plan.

**Comment by maxceem** [comment]
@vikasrohit last question, what about [admins](https://github.com/topcoder-platform/tc-project-service/blob/challenge%2F30095006/src/constants.js#L39)? Should they also be members of the project to add phases?

**Comment by vikasrohit** [comment]
No, Connect Admin and administrators can do any change to any project.

**Comment by maxceem** [comment]
To sum up:

1. We should fix the permission checking method [copilotAndAbove](https://github.com/topcoder-platform/tc-project-service/blob/challenge%2F30095006/src/permissions/copilotAndAbove.js#L11) so:
   1. User with [Topcoder admins roles](https://github.com/topcoder-platform/tc-project-service/blob/challenge%2F30095006/src/constants.js#L39) should be able to perform operations. See [example](https://github.com/topcoder-platform/tc-project-service/blob/feature/workstreams/src/permissions/workManagementForTemplate.js#L65) of checking Topcoder roles.
   2. Project members with [project member manager roles](https://github.com/topcoder-platform/tc-project-service/blob/challenge%2F30095006/src/constants.js#L24-L28) should be also able to perform the operations. See [example](https://github.com/topcoder-platform/tc-project-service/blob/feature/workstreams/src/permissions/workManagementForTemplate.js#L62) of checking Project roles.
2. We should add unit tests for [each endpoint](https://github.com/topcoder-platform/tc-project-service/blob/challenge%2F30095006/src/permissions/index.js#L43-L48) which is used by `copilotAndAbove` permission method and test the next cases:
     1. Topcoder admin users can do actions even they are not project members
     2. Copilots can do actions when they are members
     3. Copilots cannot do actions when they are NOT members
     4. Managers can do actions when they are members
     5. Managers cannot do actions when they are NOT members
     6. Account managers can do actions when they are members
     7. Account managers cannot do actions when they are NOT members

**Comment by PrakashDurlabhji** [comment]
@maxceem will it be open soon?

**Comment by maxceem** [comment]
@vikasrohit to confirm, should `account mangers` be able to add phases and so on when they are members of the project?

**Comment by maxceem** [comment]
@PrakashDurlabhji yes, it will be opened as soon as all the details are clarified. Note, as per this [Bug Bash rules](https://www.topcoder.com/challenges/30095031) we do not allow to reserve issues. As soon as this issue is open for pick up, the first who comments will take it.

**Comment by PrakashDurlabhji** [comment]
@maxceem sure i understand, whoever comments first when it is opened, issue goes to them

**Comment by vikasrohit** [comment]
> should account mangers be able to add phases and so on when they are members of the project?

No, they are restricted to manage the projecgt plan.

**Comment by maxceem** [comment]
This issue is now open for pick up.

Issue summary is provided at the comment https://github.com/topcoder-platform/tc-project-service/issues/332#issuecomment-508647388.

**Comment by romitgit** [comment]
Please assign to me

**Comment by PrakashDurlabhji** [comment]
give to me thanks

**Comment by maxceem** [comment]
Assigned to @romitgit as he was the first one to comment on this.

**Comment by romitgit** [comment]
@maxceem please unassign as I'm not able to finish this.

**Comment by maxceem** [comment]
Thanks for update @romitgit. This issue is now open for pick up.

**Comment by mfikria** [comment]
@maxceem is this issue open for public? If yes I want to work on this

**Comment by maxceem** [comment]
Yes, @mfikria, it's a part of Bug Bash https://www.topcoder.com/challenges/30095031. Assigned you.

**Comment by mfikria** [comment]
I've made a PR in

**Comment by mfikria** [comment]
@maxceem I've made a PR in https://github.com/topcoder-platform/tc-project-service/pull/336
Note that since the provided token for test in https://github.com/topcoder-platform/tc-project-service/blob/dev/src/tests/util.js limited. I simplify the test case for each endpoints into 3 cases:
- Users with admin roles can do actions even they are not project members
- Users with copilot roles cannot do actions when they are NOT members
- Users with Project manager roles can do actions if they are members

**Comment by maxceem** [comment]
Thanks, @mfikria.

> I simplify the test case for each endpoints into 3 cases:

Can we also test a case that a user with `Connect Manager` or `Connect Copilot` Topcoder roles cannot do actions to projects they are not members of?

I'm not sure if the limitations in https://github.com/topcoder-platform/tc-project-service/blob/dev/src/tests/util.js to add such tests.

**Comment by mfikria** [comment]
@maxceem do we need a jwt token with "no expiration" for test?

**Comment by maxceem** [comment]
> @maxceem do we need a jwt token with "no expiration" for test?

yes, we have them in the https://github.com/topcoder-platform/tc-project-service/blob/dev/src/tests/util.js:
- `Connect Copilot` https://github.com/topcoder-platform/tc-project-service/blob/dev/src/tests/util.js#L20
- `Connect Manager` https://github.com/topcoder-platform/tc-project-service/blob/dev/src/tests/util.js#L24

**Comment by mfikria** [comment]
@maxceem actually i used those tokens in the unit tests

**Comment by maxceem** [comment]
Yep so now we have cases:
- Users with copilot roles cannot do actions when they are NOT members
- Users with Project manager roles can do actions if they are members

And would like to also have opposite cases:
- Users with copilot roles CAN do actions when they are members
- Users with Project manager roles CANNOT do actions if they are NOT members

**Comment by mfikria** [comment]
@maxceem the case "Users with copilot roles CAN do actions when they are members" is not needed since the existing successful unit test using copilot token

**Comment by maxceem** [comment]
> @maxceem the case "Users with copilot roles CAN do actions when they are members" is not needed since the existing successful unit test using copilot token

Ok, then only `Users with Project manager roles CANNOT do actions if they are NOT members` if we don't have such test yet.

**Comment by mfikria** [comment]
@maxceem the PR has been updated.

**Comment by maxceem** [comment]
@vikasrohit this issue has been fixed and deployed with the release 2.4.13.
