### ISSUE TITLE
Timeline is not updated in ES

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#376]
It looks like timeline is not updated in ES after we update milestones.

For example:
- create timeline without `endDate`
- create a milestone
- update milestone to trigger setting `endDate` for timeline here https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/milestones/update.js#L301
- now retrieve the timeline using two ways:
   - https://api.topcoder-dev.com/v4/timelines/4369 - returns timeline from DB
   - https://api.topcoder-dev.com/v4/timelines/?filter=reference%3Dwork%26referenceId%3D6212 - returns the same timeline from ES
- requests from DB returns `endDate` as it has been updated, and requests form the ES returns `endDate = null`.

**Comment by maxceem** [comment]
Also, I've noticed that sometimes some other data in milestones is not updated inside timeline from ES. But don't have steps to reproduce.

**Comment by vikasrohit** [comment]
I have made some [changes](https://github.com/topcoder-platform/tc-project-service/tree/feature/update_timeline_in_ES_milestones_cascade) for the main issue raised in the description of the issue. Would that work @maxceem ?

**Comment by maxceem** [comment]
@vikasrohit there was one typo in the fix which I've fixed and created a PR https://github.com/topcoder-platform/tc-project-service/pull/380 for this issue.

Tested locally, working good at least for the main case described in this issue. I think we can deploy the PR to DEV, test it, and close this issues until we see any other cases where timeline updating fails.

**Comment by vikasrohit** [comment]
Thanks @maxceem for reviewing the PR. However, I don't think it was a typo, I think `assign` supports passing [multiple sources](https://lodash.com/docs/4.17.11#assign) to be copied into the destination object.

**Comment by maxceem** [comment]
The typo was regarding `data.cascadedUpdates.timeline` object which has been merged:

![image](https://user-images.githubusercontent.com/146016/64598869-1f5f5100-d3c1-11e9-853b-b754777c044b.png)

but we have to merge `data.cascadedUpdates.timeline.updated` (`updated` object inside `timeline`)

![image](https://user-images.githubusercontent.com/146016/64598907-2f773080-d3c1-11e9-94d7-5c4a967df7ad.png)

I've also slightly refactored and used `merge` instead of `assign` for timeline object, just to make sure that we are updating timeline in ES exactly the same way as in timeline-related endpoints, see https://github.com/topcoder-platform/tc-project-service/blob/feature/update_timeline_in_ES_milestones_cascade/src/events/timelines/index.js#L63

**Comment by vikasrohit** [comment]
Got it. Thanks.

**Comment by vikasrohit** [comment]
@maxceem can we close it? or some work pending?

**Comment by vikasrohit** [comment]
@maxceem closing the issue, please feel free to reopen or create new, if any thing still remaining.
