### ISSUE TITLE
[$70] Only admins should be able to update actualStartDate and completionDate of milestones

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#381]
Currently, all the users can update `actualStartDate` and `completionDate` of milestones. We should limit users who can update them, so only user with [admin roles](https://github.com/topcoder-platform/tc-project-service/blob/feature/update_timeline_in_ES_milestones_cascade/src/constants.js#L47) can update them.

For checking permissions we can reuse method [hasPermission](https://github.com/topcoder-platform/tc-project-service/blob/feature/update_timeline_in_ES_milestones_cascade/src/util.js#L757) without providing the third argument, like this:
```js
hasPermission({topcoderRoles: ADMIN_ROLES}, req.authUser)
```

We also have to write at least 4 unit tests which wold validate that:
1. non-admin users cannot update `actualStartDate`
2. non-admin users cannot update `completionDate`
3. admin users can update `actualStartDate`
4. admin users can update `completionDate`

Ref: https://github.com/appirio-tech/connect-app/issues/3210

**Comment by eppro** [comment]
I want to work on this issue

**Comment by r0hit-gupta** [comment]
Please assign me.

**Comment by r0hit-gupta** [comment]
PR at https://github.com/topcoder-platform/tc-project-service/pull/382

**Comment by r0hit-gupta** [comment]
@maxceem sorry for the huge delay. Fixing it ASAP.

**Comment by r0hit-gupta** [comment]
@maxceem  I have updated the PR. Please review now. Thanks.

**Comment by vikasrohit** [comment]
Closing.
