### ISSUE TITLE
Project "details" type is not searchable

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#412]
## Overview

In the project model, we have a `details` field which contains all the project details.
We have this property [described in ES mapping quite detailed](https://github.com/topcoder-platform/tc-project-service/blob/dev/migrations/elasticsearch_sync.js#L127-L189), so it looks like we want to search by some fields inside the `details` field.

![image](https://user-images.githubusercontent.com/146016/68925910-2f2f5300-07bf-11ea-9e83-e149c36553e7.png)

Though as per my testing we cannot search by properties inside `details` or at least no all ES features work properly.

## Research

For example, if I try to find all the projects which contain field `details`, I don't get any results:
```
curl -XGET localhost:9200/projects/_search?pretty=1 -d '
{
	"query": {
        "exists": {
            "field": "details"
        }
    }
}
'
```

Also, I don't get any results if I try to search for any field inside `details`, I will also get no results:
```
curl -XGET localhost:9200/projects/_search?pretty=1 -d '
{
   "query": {
        "exists": {
            "field": "details.hideDiscussions"
        }
    }
}
'
```

Though, I will find the project if I search project using `id` or `name`:
```
curl -XGET localhost:9200/projects/_search?pretty=1 -d '
{
   "query": {
        "exists": {
            "field": "name"
        }
    }
}
'
```

Now, as `details` field has `type: "nested"` probably I should use the query for `nested` type, but it also doesn't return any results:
```
curl -XGET localhost:9200/projects/_search?pretty=1 -d '
{
    "query": {
        "nested": {
            "path": "details",
            "query": {
                "bool": {
                    "must": [
                        {
                            "exists": {
                                "field": "hideDiscussions"
                            }
                        }
                    ]
                }
            }
        }
    }
}
'
```

## Possible issue and solution

Most likely the `details` field is not searchable and not indexed properly, because of its type set to `nested`. Though `nested` type should be used for `arrays of objects` not for objects as per [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/nested.html).
The `details` is an object, not an array of objects, so I guess setting `nested` type for it makes it be not indexed properly and thus not searchable.

If I remove `nested` from the mapping and reindex projects than I can search by `details` field so all 3 queries without `nested` work good for me and return documents.

@vikasrohit do you know if anywhere we are searching by the inner part of `details` field? Maybe I'm missing somethings and some other queries inside `details` work even now with `nested` type.

## References 

Probably connected with existent feature request https://github.com/topcoder-platform/tc-project-service/issues/15

**Comment by vikasrohit** [comment]
Yep, we are [searching](https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projects/list.js#L376) by ref code which is stored inside `details` json.

**Comment by maxceem** [comment]
Searching by data in `details` does indeed work, in particular, searching by `ref code`. 

Though I still have some concerns regarding using `type: "nested"` for `details` looks like not a correct usage of this prop for ES, and probably it may have some side effects. For example, some search requests didn't work for me, which are listed in the main issue.

So we might close this issues as we don't have any real-world issues now, or put some efforts to check it and probably adjust config for ES index to not use `nested`.

What would you prefer @vikasrohit?

**Comment by vikasrohit** [comment]
I guess we are okay for now. But as a general concern, I thought that `nested` is always better for searching. I remember some issues in past because the nested json was not actually stored as nested schema in ES.

**Comment by maxceem** [comment]
Yeah, I also remember something like this, though I don't remember the exact conditions. Ok, as we don't have any actual issues, I'm closing for now.
