### ISSUE TITLE
Admin endpoint for reindexing project doesn't index "invites"

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#416]
Admin endpoint `POST /v4/projects/admin/es/project/index` suppose to index projects from DB into ES.

Generally it works, but it doesn't add "invites" property with invites to the index even if a project has invites.

FYI @vikasrohit.

**Comment by vikasrohit** [comment]
Is it? We need to fix it.

**Comment by maxceem** [comment]
Yes. Here is what I have after I removed project from the index, and after indexed it again using admin endpoints:

![image](https://user-images.githubusercontent.com/146016/70121215-1f61ab00-16a9-11ea-9333-92e12df5333f.png)

While in the DB I can see invites, and also, invites were there before I removed the project from the index:

![image](https://user-images.githubusercontent.com/146016/70121290-3ef8d380-16a9-11ea-957c-1ee49e5ab235.png)

**Comment by maxceem** [comment]
There is another implicit proof of this.
Here is an old project in V4 dev env: https://connect.topcoder-dev.com/projects/8406 - it has an invitation.
And the same project which has been migrated to V5 https://connect-test01.topcoder-dev.com/projects/8406 - it doesn't have an invitation.

**Comment by maxceem** [comment]
This is done via https://github.com/topcoder-platform/tc-project-service/commit/84ab28f89b7b46aaae897324f4ba1f92d889f66b

**Comment by vikasrohit** [comment]
Verified.
