### ISSUE TITLE
Adding support to search project via customer/manager handles

### ISSUE THREAD

**Issue by RishiRajSahu** [topcoder-platform/tc-project-service#421]
Currently we support to search projects in ES via the customer/manager names this needs to be supported by handle as well. 
<img width="1439" alt="Screen Shot 2019-12-12 at 11 05 32 AM" src="https://user-images.githubusercontent.com/11248478/70685465-84cc2200-1ccf-11ea-8604-3a3a4abf347d.png">

fyi @maxceem @vikasrohit

**Comment by maxceem** [comment]
Sum up:
Update endpoint to LIST projects https://github.com/topcoder-platform/tc-project-service/blob/feature/es-db-compare/src/routes/projects/list.js#L326.
The general logic of this endpoint: get data from the Elasticsearch index, if nothing found, then get data from the DB. 
- Update request to ES in this endpoint so it filters projects by customers and managers, not only using first and last name, but also `handle`
- Implement 2 unit tests, that would check that filtering project by `customer` and `manager` using `handle` works
- In DB we don't have user details, so don't have to update DB request.

**Comment by maxceem** [comment]
@vikasrohit I'ts done as a part of https://github.com/appirio-tech/connect-app/issues/3496 so I think might be closed.
