### ISSUE TITLE
Create a new "PUT /v4/projects/:projectId(\\d+)/members/invites/:inviteId" endpoint 

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#422]
### Overview

At the moment we use `PUT /v4/projects/:projectId(\\d+)/members/invite` endpoint to update the invites. This endpoint doesn't have the `{id}` and we post body with either `userId` or `email` mandatory to find the actual invite to update.

This kind of endpoint doesn't follow the RESTfull format and also, doesn't work if we have email masked, so when we want to cancel invitation but we know only masked email, we send request to it with masked email, but server cannot find the invite by masked email, see related issue in Connect App https://github.com/appirio-tech/connect-app/issues/3413

**In general**, our current implementation of invite related endpoints doesn't follow the RESTfull style, and creating the current endpoint is a step towards moving to RESTfull format here.

### Task

- Implement a new endpoint which would update the invite by `invite.id`: `PUT /v4/projects/:projectId(\\d+)/members/invites/:inviteId(\\d+)` (with the `s` in the `invites` word).
- This endpoint should work the same as existent one (copy code from the existent one) but the part for finding an invite to update should be different: https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projectMemberInvites/update.js#L39-L67
- Instead of looking for invite by `userId`/`email` look for an invite by `id` with **any** invite status.
   - if no invite is found - return error 404: `Invite with id {inviteId} for project id is not found`.
   - if invite status is NOT `INVITE_STATUS.PENDING` or `INVITE_STATUS.REQUESTED` then return error `422`: `Invite in status "{invite.status}" cannot be updated.`
- continue the rest of the code as it is now.

### General requirements

- Copy and adjust unit tests for the new endpoint using existent endpoint unit test
- Additionally, create unit tests to test the case when the invite is not found by id and when it cannot be updated as it's status doesn't allow it
- Don't update Postman or Swagger files

### Verfiication

Please, provide a demo video which shows 3 cases: 
- the server returns 404 for non-existent invite, 
- the server returns 422 for invite in the status which doesn't let us update invite
- successful update of the invite

**Comment by vikasrohit** [comment]
I think this one is still pending, right @maxceem? Please feel to close it if it is done.

**Comment by maxceem** [comment]
We decided not to do this as it would pull along many other changes. This should be implemented as a more general task to unify all the invite endpoints to follow RESTful style instead of a very custom implementation at the moment.

**Comment by vikasrohit** [comment]
Agreed. Do you think we would be able to do those RESTful changes in coming 2-3 weeks? If yes, I would keep it in 2.0.1 otherwise I would move it to 2.0.2

**Comment by maxceem** [comment]
I'm closing this issue as it would be done as a part of a more general issue https://github.com/topcoder-platform/tc-project-service/issues/437.

Looks like it would not be ready for 2.0.1 as we would also have to do respective client-side changes and release them together with server-side changes.
