### ISSUE TITLE
Update Postman file

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#429]
I've noticed a few missing endpoints which would be good to have in Postman for local testing:
- Org Configs CRUDs

As was discussed below:
- Create a separate Postman collection with [Admin endpoints](https://github.com/topcoder-platform/tc-project-service/tree/master/src/routes/admin).
   - This file should NOT be included inside the repository.

**Comment by vikasrohit** [comment]
@maxceem I haven't added the admin endpoints intentionally to prevent any accidental security issue.

**Comment by maxceem** [comment]
Got it, removed them from the list. Though during local testing it would be nice to have them somewhere. I can see that now such endpoints are very helpful during local testing to delete/create indexes, and reindex data. I use them a lot. And if someone else has to test that indexing data works good, such endpoints would be very helpful.

Maybe we can put admin endpoints to a separate Postman file or something like that?

**Comment by vikasrohit** [comment]
Yep, we can have that in a separate postman file and exchange it on email for record purposes.

**Comment by maxceem** [comment]
Do you mean we shouldn't share it with the community only use ourselves?

**Comment by vikasrohit** [comment]
Not exactly. But we can share this as adhoc challenge document when it is required in a specific challenge.

**Comment by maxceem** [comment]
Sum up:
- Add to Postman file all the endpoint for https://github.com/topcoder-platform/tc-project-service/blob/feature/es-db-compare/src/models/orgConfig.js#L1 model
- See other endpoints in Posman file for reference on what kind of request we usually add for endpoints
- When we create an OrgConfig, create a variable with a created record, so it could be used in other endpoints
- See the source code of OrgConfig endpoints and add all kind of filters and possible queries
- Also, make sure, that swagger file has up to date data regarding OrgConfig endpoints or update swagger too
- Admin endpoints are out of scope.

**Comment by maxceem** [comment]
@vikasrohit Added OrgConfig endpoints. And we decided not to include admin endpoints to the repo, so I guess it can be closed for now.

![image](https://user-images.githubusercontent.com/146016/78362773-55655c00-75c3-11ea-9550-54414846a295.png)
