### ISSUE TITLE
Add support for reason for project cancelation

### ISSUE THREAD

**Issue by fnisen** [topcoder-platform/tc-project-service#44]
When a project is being canceled/closed, we'd like to add a disposition field to explain what happened. Possible options: 1) spam 2) demo/test 3) went with competitor 4) price/cost 5) not a good fit for community 6) declined by our choice 7) customer didn't make decision/never heard back 8) customer decided to do it themselves

![pasted image at 2017_02_15 02_03 pm](https://cloud.githubusercontent.com/assets/12552247/23031841/4b513d0e-f427-11e6-9dad-79dd12a06d8c.png)

**Comment by vikasrohit** [comment]
@parthshah we can store the cancellation reason at root level of the project json, right? or do you think it makes sense to store it in details field JSON?

**Comment by vikasrohit** [comment]
On the contrary to what I have said above, I have made changes in the front end, without altering the project service, to allow setting the reason of cancellation. For now I have stored the reason of status changes in `details` JSON, rationale being that essentially  it is the `detail` of the status changes. Further, I have taken the liberty to support track multiple status changes as well. These all status changes would be stored as an array of objects with following schema:
<pre>
{
  fromStatus: <previous status>,
  toStatus: <status changed to>,
  timestamp: <timestamp of change>,
  reason: <reason of the change>
}
</pre>
Despite the support being added, UI is right now only adding reason for cancellation of the project. All changes are in separate branch https://github.com/appirio-tech/connect-app/tree/feature/project-cancellation-reason

**Comment by fnisen** [comment]
Thanks @vikasrohit. @parthshah please weigh in b/c I think you were already making some API changes to be able to track status changes. Also, I think we've instrumented project service to focus on the API, so having this on the front end may mean we can't reliably pull in the data. Finally, the reason is applicable mostly for cancellation. If a project moves phases in other cases, there's usually only one reason.

**Comment by vikasrohit** [comment]
@fnisen I guess we should ask a reason for project deletion as well.

**Comment by fnisen** [comment]
@vikasrohit good idea, but I think it's not critical. Deletion is supposed to be for when you're experimenting with project creation, so we can assume for now the user was not serious about the project.

**Comment by parthshah** [comment]
@vikasrohit nice thought on using details field. Sorry I missed your earlier post. I'm running a challenge to add cancellation reason At the root level along side status. For status history tracking, you don't want to burden the client with tracking history. Besides we shouldn't trust the client to do it right. This is definitely a service concern and should be done server side. I'm not planning on exposing this data through the api either, it will only be used for our tracking. @fnisen let me know if status changes need to be displayed on FE

**Comment by parthshah** [comment]
I should have the changes in dev by Thursday eod.

**Comment by vikasrohit** [comment]
Okay. Thanks @parthshah That means I have just update my changes to update the change reason at root level instead of details json. Right?

**Comment by vikasrohit** [comment]
One more thing, the new field would be used to store reason of the cancellation of the project or reason for the last status change? I am asking this to ensure if we are going support the project deletion reason in future.

**Comment by fnisen** [comment]
@parthshah - we don't need history of status changes in the FE right now. I could see it coming in handy in the future, for example with an admin tool or timeline feature. But, I think no need to build it just in case, if it's easy enough to make the change later. 
@vikasrohit - I'm pretty sure we won't need the reason per status change, but I guess you can include it for maximum flexibility. Probably better for Parth to weigh in on this one.

**Comment by parthshah** [comment]
Field is called 'cancelReason' but can be used for delete action as well

**Comment by vikasrohit** [comment]
Thanks @parthshah for the update. Is it deployed to dev?

**Comment by parthshah** [comment]
Not yet but hope to have it deployed today

**Comment by vikasrohit** [comment]
Deployed and tested on dev. @fnisen @vic-topcoder Please let me know if you find any style issues with the changes.

**Comment by fnisen** [comment]
@vikasrohit - two notes:
1. The dropdown is initially set to "spam" and if I hit Cancel Project without changing the reason, I get an error. Can you please set the default to be blank, so it's clear that a reason needs to be selected? 
2. Also, some copy changes:
- Post-title description: "This action will permanently change the status of your project and cannot be undone." (reword and add "of")
- Drop-down caption: "Why is this project being canceled?"
- Reasons: please write these out as below, in the following order:
Spam
Demo
Customer selected competitor
Price too high
Being done in-house 
Customer not responsive
Poor community fit
Declined by us

**Comment by vikasrohit** [comment]
PR https://github.com/appirio-tech/connect-app/pull/746 created for this but waiting for the bug hunt to finish before getting it merged.

**Comment by fnisen** [comment]
@vikasrohit I think you can merge this one now because it's out of scope for the bug hunt.

**Comment by vikasrohit** [comment]
Merged.
