### ISSUE TITLE
Return no results when filtering projects by members firstname, lastname or handle

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#450]
In the V5 versions of Project Service we get data from ES first, and if there is no data, we fallback to DB.

We have ability to filter projects by members firstname, lastname or handle. Though we only have this data inside ES, as we additionally populate data in ES with members data: https://github.com/topcoder-platform/project-processor-es/blob/develop/src/services/ProcessorServiceProjectMember.js#L58-L72

But in DB we don't have information about member details, thus we cannot filter records in DB by these params.

At the moment this leads to the next issue:
- we filter project by member details, and get no results from ES
- as we don't get any results from ES, we fallback to DB and make the same request to DB
- as DB doesn't support filtering by member details, it returns all the data without filter
- as a result, instead of getting no data for the request we get all the data

### Proposed solution

As it's very hard to implement such filtering for DB, and we don't really need it, as 99% we would get data from ES, I suggest, that if we filter data by members firstname, lastname or handle and we don't get any data from ES, we shouldn't fallback to DB, and just return no data.

**Comment by maxceem** [comment]
This issue has been observed on DEV https://github.com/appirio-tech/connect-app/issues/3520.

We also should take care of searching by `keyword` as `keyword` is searching by all the fields, including member first and last name.

**Comment by vikasrohit** [comment]
Agreed. We should not default to DB in this case. Can we determine (without making any extra query) that if the no results is happening because of filters only or if the ES is empty?

**Comment by maxceem** [comment]
> Agreed. We should not default to DB in this case. Can we determine (without making any extra query) that if the no results is happening because of filters only or if the ES is empty?

I didn't come across with such ES ability. Looking at the ES response I don't see a possible field for such data.

**Comment by vikasrohit** [comment]
Okay. Then, we have to stop fallback to DB whenever there is at least one query param (filter) is provided, right?

**Comment by maxceem** [comment]
> Okay. Then, we have to stop fallback to DB whenever there is at least one query param (filter) is provided, right?

DB supports all the `filter` param except filtering by member first/last name or handle. So we should stop falling back to DB only if one of the next filters is defined:
- `customer`
- `manager`
- `keyword` - as keyword also filters by member details

We can keep the rest of the filters as DB already supports them.

**Comment by vikasrohit** [comment]
I was thinking of keeping it simple, assuming that having any filter might create such situations in future. It might make debugging relatively easy because we would be sure that if there is a filter and the result set is empty while it should not be empty, we are missing or inconsistent data in ES. What do you think?

**Comment by maxceem** [comment]
> I was thinking of keeping it simple, assuming that having any filter might create such situations in future. It might make debugging relatively easy because we would be sure that if there is a filter and the result set is empty while it should not be empty, we are missing or inconsistent data in ES. What do you think?

Agree, I think it makes sense. Otherwise debugging would be much trickier.

**Comment by maxceem** [comment]
@vikasrohit to properly handle https://github.com/appirio-tech/connect-app/issues/3496 and avoid confusion during testing this issue has been fixed and pushed to `develop`.
