### ISSUE TITLE
Support filtering project by directProjectId

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#456]
Feature request form @rootelement:
Add the ability to filter projects by `directProjectId`.

**Comment by maxceem** [comment]
It's done via commit https://github.com/topcoder-platform/tc-project-service/commit/efaaf84d0ac51a1a8f3b8f0420d140c7af03f4af

- ES query updated
- Swagger updated
- DB query updated to support `directProjectId` too, even though in real life we don't fallback to DB if there are any filters. Just to keep the DB query as close to ES as possible in a case in the future we would like to fallback to DB.

**Comment by vikasrohit** [comment]
Deployed to production
