### ISSUE TITLE
Refactor file transfer functionality

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#461]
- use AWS SDK instead of AWS CLI via `exec` for transferring files between buckets
- remove a redundant call for `${fileServiceUrl}uploadurl` which we don't need anymore in Project Service

This refactoring shouldn't change any functionality and only improves internal code.

**Comment by maxceem** [comment]
How to test:
- file uploading should work as before
- uploading file to some project https://connect.topcoder-dev.com/projects/8600/assets
- after uploading click the file to open/download it and make sure it works

**Comment by lakshmiathreya** [comment]
@nithyaasworld

**Comment by SathyaJayabal** [comment]
@maxceem , I was able to upload, edit and remove files from the assets library of a project in PROD.

**Comment by vikasrohit** [comment]
Closing the issue.
