### ISSUE TITLE
Update node versions to the latest

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#492]
We are currently using node v8 which is not longer maintained, see [Node maintanance schedule](https://nodejs.org/en/about/releases/)

![image](https://user-images.githubusercontent.com/146016/75510030-7c5ccb00-5a24-11ea-9644-3de2650dc9dc.png)

I would suggest updating to the latest version node v12.
It would be good to make this for all the repositories we are responsible for.

**Comment by vikasrohit** [comment]
Is it something we can do in this release @maxceem ?

**Comment by maxceem** [comment]
@vikasrohit I think yes. Though I gave it a try looks like the package `memwatch-next` that we use for detecting memory leaks doesn't support node 9+ and is abandoned https://github.com/marcominetti/node-memwatch/issues (latest version was released 4 years ago https://www.npmjs.com/package/memwatch-next).

Do we still use it and have to find a replacement first or we can remove it?

**Comment by vikasrohit** [comment]
I don't think we need it now and at least immediately. But it might be helpful to find an alternative in parallel.

**Comment by maxceem** [comment]
Done via PR https://github.com/topcoder-platform/tc-project-service/pull/531

**Comment by codejamtc** [comment]
@maxceem @vikasrohit Please check. I have created a few projects using some user roles.
https://monosnap.com/file/ZBMlM4kjT9TqTMVOWUPEIqJz5Gzpkl

**Comment by maxceem** [comment]
Thanks, @codejamtc. I think all good with this ticket.

**Comment by codejamtc** [comment]
@maxceem 👍 I am unable to change the label, I think I don't have permission
You can change it to `Pass on Dev QA`

**Comment by vikasrohit** [comment]
Closing. @codejamtc I am marking it as QA Pass for prod because the updated release is working fine and our standard smoke tests worked fine after the release.
