### ISSUE TITLE
Fix searching projects by handle 

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#499]
In another issue, we've enabled searching projects by "handle" https://github.com/topcoder-platform/tc-project-service/issues/421

Though, it appears the search by the handle is case-sensetive, but should be case-insensitive:
- open https://connect.topcoder-dev.com/projects
- there is project `8846` which has customers: `TCConnCopilot`, `tcconnBDR`, `TCConCopilotMgr ` and managers: `TCConAccountMgr`, `TCConManager`, `pshah_manager`
- though we only can find this project when we are searching by manager `pshah_manager`, but cannot find it searching by customer or manager handles with upper-case letters.
- most likely it's due to using `not_analyzed` for the `handle` as we CAN find these projects using user name with upper-case letters https://github.com/topcoder-platform/tc-project-service/blob/cf21/src/utils/es-config.js#L244 which should be removed
- create 2 unit test which would check that searching by handle works case-insensitive:
    - find a project with a member with a lowercase handle using an upper-case filter
    - find a project with a member with an uppercase handle using a lower-case filter

**Comment by vikasrohit** [comment]
@maxceem Closing. Please feel free to make it open again if some work is pending.
