### ISSUE TITLE
M2M support for updating billingAccountId for the project

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#529]
We need to support updating billingAccountId for the project via m2m calls which I think is already supported. However, right now that is not restricted as of now and any one in the project team can update that field. It was okay till now because we were not syncing that back to the legacy project, but now we have to sync that back to the legacy https://github.com/topcoder-platform/legacy-project-processor/issues/13, so we have to restrict update of the field only for certain user roles like we are doing [here](https://github.com/topcoder-platform/tc-project-service/blob/develop/src/routes/projects/update.js#L145) for directProjectId and possibly to a dedicated scope via m2m call.

**Comment by vikasrohit** [comment]
@maxceem fyi

**Comment by maxceem** [comment]
@vikasrohit it's now possible to implement it after https://github.com/topcoder-platform/tc-project-service/pull/555.

I would suggest using common scope like `write:projects` for consistency. But we also can add some dedicated scope if you like. In such case let me know how to name it.

**Comment by vikasrohit** [comment]
I would like to use specific scope (`write:projects-billing-accounts`) for this purpose because it is a privileged action and I don't want any app which has write access to the project to be able to update the billing account as well. I guess we need to make both scopes (`write:projects` and `write:projects-billing-accounts`) required to update billing account or do you think should we require `write:projects` for all fields of project except `billingAccountId` and `write:projects-billing-accounts` for writing `billingAccountId` field only?

**Comment by maxceem** [comment]
@vikasrohit I think we should require both. It would be also more easier and straightforward to implement from the technical point of view.

**Comment by vikasrohit** [comment]
Go for it. I think it would make it easier to get rid of this additional scope in future in case if other stakeholders think that it is not as per standards.

**Comment by maxceem** [comment]
Overview:
We shouldn't allow setting or updating `billingAccountId` to regular users.

Sum up:
- create a new permission definition `MANAGE_PROJECT_BILLING_ACCOUNT_ID` in https://github.com/topcoder-platform/tc-project-service/blob/899be6a10f2540f5c879fbf7010e9e0c77a58a82/src/permissions/constants.js
   - the permission should be the same as `UPDATE_PROJECT_DIRECT_PROJECT_ID`, but replace scope `write:projects` with `write:projects-billing-accounts`
   - give appropriate name and description, see [permissions guide](https://github.com/topcoder-platform/tc-project-service/blob/develop/docs/guides/permissions-guide/permissions-guide.md)
- inside POST and PATCH endpoints we should only let to set or update `billingAccountId` if user has permission `MANAGE_PROJECT_BILLING_ACCOUNT_ID`.
- create a unit test in POST and PATCH endpoints, that would check, that when we use M2M token without scope `write:projects-billing-accounts` we cannot update `billingAccountId`

Additional:
- rename permission `UPDATE_PROJECT_DIRECT_PROJECT_ID` to `MANAGE_PROJECT_DIRECT_PROJECT_ID` and update its title and description accordingly.
- to keep it consistent and safe, don't allow to setting `directProjectId` inside `POST` endpoint. As now we don't allow updating `directProjectId`, but any user can still set it during creating.

**Comment by maxceem** [comment]
@vikasrohit this is done via PR for DEV https://github.com/topcoder-platform/tc-project-service/pull/564. (We can create a hotfix from the same branch if needed).

I have one question before merging to DEV: as we require a special scope for updating `billingAccountId`, should we also require a special scope for updating `directId`?

![image](https://user-images.githubusercontent.com/146016/81141837-79c3a800-8f76-11ea-9da9-5438e41a0bef.png)

**Comment by vikasrohit** [comment]
Great!! We don't need it for direct id as of now. However, the permission HTML, I guess, it is not showing the `write:projects` which is also necessary for a m2m app to update the billing account along with `write:projects-billing-accounts` scope.

**Comment by maxceem** [comment]
> However, the permission HTML, I guess, it is not showing the write:projects which is also necessary for a m2m app to update the billing account along with write:projects-billing-accounts scope.

@vikasrohit This is due to the logic of `scopes` field. We allow to perform the action if ANY of the scopes present. So if we add `write:projects` there, then everyone who has scope `write:projects` would be able to update the billing account.

Though by fact the logic of update project endpoint is like this: first we check if user can update project in general which requires `write:projects` and after we check if user has permission to update particular field by checking if user has scope `write:projects-billing-accounts`. So it works now as we want, but there is no way for now to reflect this fact in the permissions HTML file. I guess we could think about it after we implement all the permissions inside Project Service using this new unified way. When we have all the permissions in HTML we could see the whole picture and try to improve such moments.

**Comment by vikasrohit** [comment]
Makes sense. Just wanted to clarify my doubt.

**Comment by maxceem** [comment]
It is merged to DEV.
And for PROD we have a hotfix https://github.com/topcoder-platform/tc-project-service/pull/565

**Comment by vikasrohit** [comment]
Closing the issue to mark the work as done. However, we currently have it is disabled because of some prod issue. we can re-enable it when needed.
