### ISSUE TITLE
Enable some eslint rules again and update the code to follow them

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#538]
During updating eslint to 6.8.0 version I had to disable some rules to avoid multiple changes across the codebase, as we have branch `feature/bulk-milestone-updates` with quite wast changes, to avoid merge conflicts later.

After we merge `feature/bulk-milestone-updates` to `develop` we should re-enable the eslint rules disable in this PR https://github.com/topcoder-platform/tc-project-service/pull/537/files#diff-1dc6ee56b778cd91e0327b52aaeaa1b9 and fix the source code accordingly.

**Comment by maxceem** [comment]
@vikasrohit this is done via PR https://github.com/topcoder-platform/tc-project-service/pull/566.

Before merging it, I would like to confirm, that there is no one working on a big change in Project Service. Because this PR contains a lot of trivial fixes to formatting which might cause merge conflicts.

Note: existent big PR https://github.com/topcoder-platform/tc-project-service/pull/540 would be updated, so this one is under control.

**Comment by vikasrohit** [comment]
Yep, we don't have any other major feature as of now in progress.

**Comment by vikasrohit** [comment]
@maxceem should we merge #566 before #540?

**Comment by maxceem** [comment]
> @maxceem should we merge #566 before #540?

Yes, #540 is waiting for client-side changes so we cannot merge it yet. I would keep it in sync with `develop` branch.
