### ISSUE TITLE
Invite is not working for unregistered user

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#548]
When an unregistered user is invited to a project and then if invited user registers and tries to load the project, it is expected to show the Join Dialog to allow user to accept the invite, however, as of now it seems to throw 404 and skips the Join Dialog.

**Comment by coderhacker** [comment]
Tested on dev env. https://connect.topcoder-dev.com/
Working as expected, please find an attached video for testing. 
1. User : topcoderconnect+CopilotManager/appirio123
2 User : taxt123412/Test@1234

Attached screenshot:
[548_dev-connect-pass.zip](https://github.com/topcoder-platform/tc-project-service/files/4492729/548_dev-connect-pass.zip)

**Comment by coderhacker** [comment]
@maxceem @vikasrohit I have not to edit access to change the level for ticket. However, this is pass on dev env.

**Comment by vikasrohit** [comment]
@maxceem merged the fix for this issue in dev as well few minutes ago, so you might not see the error there now.

**Comment by maxceem** [comment]
@coderhacker you suppose to have access to change the labels for tickets, could you give it a try?

**Comment by coderhacker** [comment]
@maxceem nope please see 
![image](https://user-images.githubusercontent.com/62358241/79569012-7f933f80-80d4-11ea-9452-2b45d7ae6f10.png)

**Comment by maxceem** [comment]
Ah, yes, it's another repo, I've confused with Connect App.

**Comment by coderhacker** [comment]
Okie, Could you please give me access so that I can change the label. @maxceem

**Comment by drasticdpk** [comment]
verified on prod env :
![image](https://user-images.githubusercontent.com/25297859/79570673-9e480500-80d9-11ea-8020-734708d456c8.png)
@maxceem if possible add me and **codejamtc** too on this repo.
