### ISSUE TITLE
Error while updating a project

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#582]
Following error appears when trying to PATCH a project (6450 in dev). Template id of the project is `5` which might not be active now. If that is the case we might need to handle it gracefully, otherwise need to fix it.

```
{
    "name": "tc-projects-service-dev",
    "hostname": "31f9b98aeb22",
    "pid": 37,
    "requestId": "09c92525-2534-4677-ad33-b34c72547dfa",
    "level": 50,
    "err": {
        "message": "Cannot read property 'form' of null",
        "name": "TypeError",
        "stack": "TypeError: Cannot read property 'form' of null\n    at /usr/src/app/dist/models/projectTemplate.js:53:30\n    at Immediate._onImmediate (/usr/src/app/node_modules/async-listener/glue.js:188:31)\nFrom previous event:\n    at Function.ProjectTemplate.getTemplate (/usr/src/app/dist/models/projectTemplate.js:52:64)\n    at /usr/src/app/dist/routes/projects/update.js:224:47\nFrom previous event:\n    at /usr/src/app/dist/routes/projects/update.js:216:8\n    at /usr/src/app/node_modules/sequelize/lib/sequelize.js:1106:21\n    at Immediate.<anonymous> (/usr/src/app/node_modules/async-listener/glue.js:188:31)\n    at processImmediate (internal/timers.js:456:21)\n    at process.topLevelDomainCallback (domain.js:137:15)\nFrom previous event:\n    at /usr/src/app/node_modules/sequelize/lib/sequelize.js:1106:10\n    at Function._clsRun (/usr/src/app/node_modules/sequelize/lib/sequelize.js:1150:21)\n    at Sequelize.transaction (/usr/src/app/node_modules/sequelize/lib/sequelize.js:1104:22)\n    at module.exports (/usr/src/app/dist/routes/projects/update.js:210:30)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)\n    at module.exports (/usr/src/app/dist/routes/projects/update.js:192:5)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)\n    at /usr/src/app/node_modules/tc-core-library-js/lib/middleware/permissions.js:10:9\n    at propagateAslWrapper (/usr/src/app/node_modules/async-listener/index.js:504:23)\n    at /usr/src/app/node_modules/async-listener/glue.js:188:31\n    at /usr/src/app/node_modules/async-listener/index.js:541:70\n    at /usr/src/app/node_modules/async-listener/glue.js:188:31"
    },
    "msg": "Cannot read property 'form' of null",
    "time": "2020-10-05T12:36:19.908Z",
    "v": 0
}
```

**Comment by vikasrohit** [comment]
fyi @RishiRajSahu

**Comment by maxceem** [comment]
@vikasrohit apart from fixing this error in Project Service, we also have to handle it on the client-side somehow. At the moment when I open such a project I see an infinite loading page because Project Template is indeed not found, and we don't know how to display the project (https://connect.topcoder-dev.com/projects/6450):

![image](https://user-images.githubusercontent.com/146016/95087586-8cf7c100-072a-11eb-8b87-5cbf329a1ac4.png)

Btw, how did you call the `PACH` request if Connect App cannot open this project?

**Comment by maxceem** [comment]
@vikasrohit it's fixed by PR https://github.com/topcoder-platform/tc-project-service/pull/583. Fix verified locally.

**Comment by vikasrohit** [comment]
> @vikasrohit apart from fixing this error in Project Service, we also have to handle it on the client-side somehow. At the moment when I open such a project I see an infinite loading page because Project Template is indeed not found, and we don't know how to display the project (https://connect.topcoder-dev.com/projects/6450):
> 
> ![image](https://user-images.githubusercontent.com/146016/95087586-8cf7c100-072a-11eb-8b87-5cbf329a1ac4.png)
> 
> Btw, how did you call the `PATCH` request if Connect App cannot open this project?

Yes, UI also needs the fix. One of the event processors which consumes salesforce events and updates the v5 project, is making the PATCH request.

**Comment by maxceem** [comment]
Created a follow-up issue for [another issue](https://github.com/topcoder-platform/tc-project-service/issues/582#issuecomment-703654821) found on the client https://github.com/appirio-tech/connect-app/issues/4207

This issue might be closed.

**Comment by RishiRajSahu** [comment]
Thanks @maxceem
