### ISSUE TITLE
Update type of the field "terms" in Project model to array of strings

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#614]
At the moment project model has field `terms` which accepts an array of integers as value, like `[1, 2, 3]` because old Terms Ids were integers. New Terms ids are string (UUID). So we have to update this field type to accept an array of strings.

As we don't use this field so far, there should be no values in this field, and even if we have some values we can remove them. So we don't need to migrate any existent data.

- Update model.
- Update Swagger and Postman if needed.
- Create SQL migration script.
- Update ES Processor and ES mapping.
- Update unit tests.
- Update Joi Schemas in all endpoints.

#### References
- This update is to support changes in Connect App https://github.com/appirio-tech/connect-app/issues/4273#issuecomment-765292459

**Comment by vikasrohit** [comment]
Deployed to prod
