### ISSUE TITLE
Add field "groups" in Project model

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#616]
This field should be optional with default value of `[]`. It should allow array of strings (for group ids which are UUIDs).

- Update model.
- Update Swagger and Postman if needed.
- Create SQL migration script.
- Update ES Processor and ES mapping.
- Update unit tests if necessary.
- Update Joi Schemas in all endpoints.

#### References
- This update is to support changes in Connect App https://github.com/appirio-tech/connect-app/issues/4270#issuecomment-765344461

**Comment by vikasrohit** [comment]
Deployed to prod.
