### ISSUE TITLE
New API endpoint to bring Billing Accounts available to the logged in user

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#620]
For supporting the selection of appropriate billing account per project level, we need to provide list of available billing accounts to the logged in user so that he/she can choose from it and set it for the project. As per agreed decision after brainstorming with multiple stakeholders, we settled to implement this endpoint in the projects api itself instead of using v3 billing account api or creating separate api for calling SFDC api to bring the BA information.
This new endpoint would return all BA for the logged in user i.e. all the BAs that the logged in user is part of (as resource).

**Comment by maxceem** [comment]
### Unit Tests to create:

- `should return 403 for anonymous user`
- `should return 403 for a regular user who is not a member of the project`
- `should return billing accounts for a regular user who is a member of the project`
- `should return all billing accounts to admin`
- `should return all billing accounts using M2M token with "read:user-billing-accounts" scope`

**Comment by maxceem** [comment]
@vikasrohit could you please go through the test cases above and confirm if these are what is expected.

**Comment by vikasrohit** [comment]
> should return all billing accounts for a regular user who is a member of the project

I think it should be available only to topcoder team. Customers won't be able to see available BAs.

**Comment by maxceem** [comment]
ok, I've updated the comment https://github.com/topcoder-platform/tc-project-service/issues/620#issuecomment-776852879
