### ISSUE TITLE
Support different "originators" of member invitations

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#623]
### Context

We have functionality to invite members to the Topcoder Projects inside [Connect App](https://connect.topcoder-dev.com/) which looks like [this](https://monosnap.com/file/QSMsBEwEMi4bmq85H1JOJg0MOa6pB4). When users are invited they also receive a email notifications with links to accept or decline invitation as on [screenshot](https://monosnap.com/file/LyTZa9aFlpchyxuR3KmiuUSwrW8yBv). This email is styled for Connect App, and links to **decline** and **accept** invitation lead to [Connect App](https://connect.topcoder-dev.com/). At the moment we are implementing functionality to invite members to the same Topcoder Projects inside another application called [TaaS App](https://platform.topcoder-dev.com/taas/myteams). It uses the same Projects API to invite members. As a result user get the same emails with links to Connect App.

#### General Task

We have to update Projects API and related services so when invited members we can indicate which application invited members so users would get different email notifications with links and styles for the corresponding application **Connect App** or **TaaS App**.

#### Current Workflow

- User creates invite in Projects API via endpoint "POST /v5/projects/:projectId/invites"
- Projects API sends 2 Kafka Events:
  - Event for **Notifications Service** **"connect.notification.project.member.invite.created"** ([source code](https://github.com/topcoder-platform/tc-project-service/blob/develop/src/events/busApi.js#L997-L1004)) - for each invite by **email** or by **handle**.
  - Event for **Email Service** **"connect.notification.email.project.member.invite.created"** ([source code](https://github.com/topcoder-platform/tc-project-service/blob/develop/src/routes/projectMemberInvites/create.js#L402))  - only if user doesn't exist yet and is invited by **email**.
- **Notifications Service** listens to this Kafka Event **"connect.notification.project.member.invite.created"** and if email notifications are enabled for the user it send another Kafka Event **"connect.notification.email.project.notifications.generic"** to the **Email Service** ([source code](https://github.com/topcoder-platform/tc-notifications/blob/dev/connect/notificationServices/email.js#L376-L382)).
- **Email Service** consumes these events **"connect.notification.email.project.member.invite.created"** and **"connect.notification.email.project.notifications.generic"** and sends email using Sendgrid.
- Email is send using a template that we put into the Sendgrid config. This template we generate using code inside Notification Service, see its [README](https://github.com/topcoder-platform/tc-notifications/blob/dev/emails/README.md).

#### Task Details

1. Update endpoint "POST /v5/projects/:projectId/invites" so it accepts an **optional** query param "originator". This param would define which service is invited user.
2. Pass this param inside payloads of the Kafka Events so we can know the value inside **Email Service** and it should pass this value to the Sendgrid
3. Update code inside https://github.com/topcoder-platform/tc-notifications/tree/dev/emails so we can have multiple folders there for each "originator". For now we would have folders "connect" and "taas". Put all the current templates into "connect". And create a copy of the same templates for "taas". Iniside "taas" folder only keep templates for invites, and remove all other templates as we don't send emails for "taas" in other cases. Update the code of invite templates for "taas" so it all the texts says "TaaS App" instead of "Connect". And all the links lead to the TaaS App, instead of the Connect App.
  - Update template generation logic. The final template which is generate should include templates for Connect App and for TaaS App inside, because we are putting this template into Sendgrid in one place. This final template should generate email for Connect App or TaaS App based on the value of the "originator" which is send from Email Service to Sendgrid.

**Comment by nkumar-topcoder** [comment]
cc: @RishiRajSahu @vikasrohit

**Comment by RishiRajSahu** [comment]
@maxceem looks good to me we are not much altering the flow except the new **optional** param `originator`, only one question
- Do need to create separate template ? I guess we can simply put if condition like we do for ref-codes to send different mails wrt originator.

**Comment by maxceem** [comment]
> Do need to create separate template ? I guess we can simply put if condition like we do for ref-codes to send different mails wrt originator.

@RishiRajSahu on the one hand it would be technically easier. But I can see many places which has to be updated depend on the `originator`, see screenshot below:
- in TaaS App instead of **Project** we call it **Team**
- we have to update "Connect" to "TaaS" everywhere together with the description
- we might want to update or remove Notification Settings link

![image](https://user-images.githubusercontent.com/146016/107521059-c2ba2400-6bba-11eb-8688-6aedc15e52cd.png)

So to update all these places we would have put many conditions across the templates to check if it's TaaS or Connect app. And if tomorrow we add the 3rd application, these conditions would become even more complex.

So to make the logic general and straightforward I suggest create folders per each `originator`. So template would be generated per each originator separately.

But, at the end all these templates would be combined into one single template which we add to the Sendgrid, which would look like this:
```
{{if originator === "TaaS"}}
{{include tempaltes/taas.html}}
{{elseif originator === "Connect"}}
{{include tempaltes/connect.html}}
```

**Comment by maxceem** [comment]
The requirements in TaaS App have been [changed](https://github.com/topcoder-platform/taas-app/issues/14#issuecomment-777586282), so we don't need this anymore.
So closing this.
