### ISSUE TITLE
Create Jobs in TaaS using user token instead of M2M

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#624]
We have one issue with the current way of creating Jobs in TaaS API from Projects API Kafka Consumer https://github.com/topcoder-platform/tc-project-service/blob/develop/src/events/projects/index.js#L24

At the moment when the user creates a project using Connect Intake Form, the Jobs are created by Projects API Kafka Consumer using M2M token.

But there is a restriction in TaaS API: users can only edit jobs they created. As a result, when a regular user creates jobs using Connect Intake form, such jobs are created using M2M token, and then a user who created them, cannot edit them, because in TaaS API such user is not set to `createdBy` .

To fix this issue we have to create Jobs in Projects API using user token from the request instead of the M2M token. But there is a tricky moment, we don't pass user token inside Kafka Events.

So I think the best way to fix it is to move the logic of creating Jobs on projects creation from Kafka Event to the internal Event Emitter and handle job creations here https://github.com/topcoder-platform/tc-project-service/blob/develop/src/events/busApi.js#L57-L64. At this point, we have access to the request objects so we can use user token, and this logic would be still quite decoupled from the main project creation logic.

**Comment by maxceem** [comment]
As a part of this issue fixing we have to test locally, that when `POST` request with data from this form https://connect.topcoder-dev.com/new-project/taas-jobs the jobs are created successfully in TaaS using user token.

**Comment by maxceem** [comment]
The code of the event emitter works synchronously. So if this code we mote to the handler throws expectation it would cause POST request to fail.

We have to make sure that all the code is wrapped in try/catch, and or promises have catches. So if any error during this code happens it should be logged as an error, but it should not break/stop code from the executing.

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/tc-project-service/pull/626 and https://github.com/topcoder-platform/tc-project-service/commit/8f0e752d83f57b70cf12a84f2f542202387d1ccd

**Comment by coderhacker** [comment]
**QA Comments**: this is passed on DEV

![image](https://user-images.githubusercontent.com/62358241/107948375-bd454b00-6fb9-11eb-87ba-2a18869b5297.png)

**Comment by coderhacker** [comment]
cc @lakshmiathreya

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/111732031-0ee23d80-88b8-11eb-93d0-7580618eee44.png)
