### ISSUE TITLE
Pass "duration" from Intake Form to TaaS Jobs

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#625]
When we create jobs using TaaS Intake Form https://connect.topcoder-dev.com/new-project/taas-jobs we are passing duration for each Job.

Previously, we didn't have a place in TaaS Job API to store this duration. But we've added "duration" field to the jobs recently https://github.com/topcoder-platform/taas-apis/issues/143.

So now when creating Job in TaaS API during project creating we have to also pass "duration" as an **integer number** https://github.com/topcoder-platform/tc-project-service/blob/develop/src/events/projects/index.js#L204-L213

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/tc-project-service/pull/626 and https://github.com/topcoder-platform/tc-project-service/commit/8f0e752d83f57b70cf12a84f2f542202387d1ccd

**Comment by coderhacker** [comment]
QA Comments: This is pass on dev please find below-attached video


https://user-images.githubusercontent.com/62358241/107946607-44dd8a80-6fb7-11eb-963f-ea867bd855dd.mp4

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/111732107-2faa9300-88b8-11eb-985d-5793b415ec33.png)
