### ISSUE TITLE
Need details of billing account for the project for the purpose of invoicing

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#636]
To provide invoicing for pure v5 challenges, we need to provide some way to determine the markup of a billing account that is associated with a v5 project.

**Comment by vikasrohit** [comment]
We are proposing a new endpoint `v5/projects/:id/billingAccount` which would return the any further requirement that we need from billing account of a particular project. This endpoint would be accessible with only m2m tokens having appropriate scopes.
Excerpts from Slack conversations regarding the rationale behind having separate endpoint instead of just syncing the details to project model with events.

```
v5/projects/1234/billingAccount is something which we are thinking to build to support fetching more details about billing accounts. and it is no where in dev or prod yet.
> I would think that we’d just add the markup to the record as well (and treat security as what data gets returned based on the incoming token - this is our general model for several APIs)?

I agree but that is true mainly when the new field (markup in our case) primarily belongs to our object (project in our case). However, IMO, markup belongs to BA and I don't want to keep every field of BA on the project level because it might pollute the data model of project and we have to put more and more security measures in returning such fields if they contains sensitive information like markup. Further, every time we need more details on BA, we have to update the project model and its various endpoints. And syncing multiple fields is always going to increase the points of failure in syncing (events based). On the contrary, if we have a dedicated endpoint for fetching more sensitive information about the BA, we can keep all logic related to that in that single endpoint without worrying about leaking the sensitive data. Further, we can limit this endpoint to be called only internally (within our AWS network). It would created single source of truth, SFDC compared to multiple source of truths if we sync all fields from BA to project. If some data is not as expected in that endpoint, we are sure that we have to look into SFDC and it would save a lot debugging time
```.

**Comment by maxceem** [comment]
### Unit Tests to create:

- `should return 403 for anonymous user`
- `should return 403 for admin`
- `should return billing account details using M2M token with "read:project-billing-account-details" scope`

**Comment by imcaizheng** [comment]
@maxceem PR created https://github.com/topcoder-platform/tc-project-service/pull/638

**Comment by maxceem** [comment]
Also, updated data format `tcBillingAccountId` is returned as an integer value for consistency with other endpoints via https://github.com/topcoder-platform/tc-project-service/pull/637/commits/e1664e362c4964f2eeccfbdaeb81692e0f1f42eb
