### ISSUE TITLE
Name field is not returned for Billing Account endpoint

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#640]
Previously we did a hotfix for this issue https://github.com/topcoder-platform/tc-project-service/issues/631.
But the hotfix breaks it in DEV.

We have to fix this issue so it works good in both DEV and PROD.

**Comment by maxceem** [comment]
Fixed by https://github.com/topcoder-platform/tc-project-service/commit/8df5f2ba11c874544da8628f4e0e03fadd511eda

**Comment by vikasrohit** [comment]
Working fine in dev and prod both now.
