### ISSUE TITLE
Return BA status in the GET billing account endpoint

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#651]
To enable the Billing Account Protections in Work Manager and Connect App, we have to return status of BA in the GET billing account endpoint.

**Comment by vikasrohit** [comment]
fyi @ajefts

**Comment by drasticdpk** [comment]
verified. 
![image](https://user-images.githubusercontent.com/25297859/120649031-069fa480-c49c-11eb-8366-569d0adb104c.png)
we have verified the integration of WM APP and for connect we will verify once it is integrated. for now I am closing it. If anything , we can open it. cc @vikasrohit
