### ISSUE TITLE
New model for storing project types in the database

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#87]
Till date we are maintaining the project types (aka categories) in JSON mapping in each project we need it. Now we are moving it to the database to make all services independent of keeping them in sync for this JSON mapping.

Requirements:

1. New model ProjectType backed by table `project_types` with only two fields `key` and `displayName` 
2. Simple CRUD operations on top of it
    1. GET /v4/projectTypes to list all available project types (no filtering and no sorting)
    2. ~~GET /v4/projectTypes/{key} to fetch specific project type details~~
    3. POST /v4/projectTypes to create new project type
    4. PATCH /v4/projectTypes/{key} to update existing project type
    5. DELETE /v4/projectTypes/{key} to delete existing project type
3. Only users with `administrator` or `Connect Admin` roles should be able to allow create new project type or update/delete existing one.

**Comment by ngoctay** [comment]
@vikasrohit @coderReview 

`key` will be something like app_dev, generic, visual_prototype, visual_design, website, app, quality_assurance, or chatbot. Right?

**Comment by coderReview** [comment]
@ngoctay I think key can be any string. I don't we have to limit it.

**Comment by vikasrohit** [comment]
Yes, those are currently possible values, but this table is a look up
table, so we don't have to limit the values.

**Comment by ngoctay** [comment]
I made PR. Please help to review.

https://github.com/topcoder-platform/tc-project-service/pull/88

**Comment by coderReview** [comment]
@ngoctay will look into this. Thanks

**Comment by ngoctay** [comment]
I still added this endpoint. Please let me know if I need to remove it.

> ~~2. GET /v4/projectTypes/{key} to fetch specific project type details~~

**Comment by vikasrohit** [comment]
Thanks ngoctay for coming back in 48 hours. Let's keep that endpoint as
well. We will take care of it internally.

On Jun 1, 2018 1:31 AM, "ngoctay" <notifications@github.com> wrote:

I still added this endpoint. Please let me know if I need to remove it.

2. GET /v4/projectTypes/{key} to fetch specific project type details

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/topcoder-platform/tc-project-service/issues/87#issuecomment-393661760>,
or mute the thread

**Comment by vikasrohit** [comment]
Closing as it is finished.
